---
title: "STAT 545A Assignment 03: dplyr/ggplot2 Part II"
---

__Due October 1, 2019 at 23:59__


## Overview

The goal is to manipulate and explore a dataset with the `dplyr` package, complemented by visualizations made with `ggplot2`. You can think of this as a deeper version of Homework 02.

## Setup

Work with the `gapminder` data we explored in class, or more than one data set if you want.

The Gapminder data is distributed as an R package from [CRAN](https://cran.r-project.org/web/packages/gapminder/index.html). Install it if you have not done so already, by executing the code `install.packages("gapminder")`, and remember to load it with `library(gapminder)`.

Install and load `dplyr`, probably via the `tidyverse` meta-package.

## Tidy Submission (16%)

### Mechanics (5%)

Follow the instructions for making a tidy submission, found on the [assignments home page](https://stat545.stat.ubc.ca/evaluation/assignments).

If there's any further uncertainty in determining a grade for this "mechanics" portion, the [UBC MDS mechanics rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_mech.md) will be referred to.

### Writing (5%)

- You must use proper English, spelling, and grammar.
- You should write concisely. 
- If there's any further uncertainty in determining a grade here, the [UBC MDS writing rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_writing.md) will be used.

### GitHub Pages (6%) **NEW**

From now on, whenever you produce an HTML file output, you are expected to make it viewable as a webpage -- for example, through GitHub Pages. There are / will be instructions added to the [assignments home page](https://stat545.stat.ubc.ca/evaluation/assignments/) on how to do this with GitHub Pages. 

You should also provide links to these HTML pages in an easy-to-find location, __and__ use words to describe what the link brings you to -- probably in a `README.md` file in your `hw03` folder. Remember, make your homework submission informative to someone who doesn't know anything about your homework repository -- do not rely on the contextual knowledge that the teaching team has about your homework submission.

For this homework assignment, you are expected to produce at least one html page, and link to it. You might not be required to submit an html page for future assignments, but if you do, you will be expected to link to them.

## The Assignment (84%)

-----
Rubric for each task:

- [code quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md): (10%)
	- Did you use the tidyverse (dplyr, ggplot2) where appropriate?
- [vis quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_viz.md): (9%)
	- Did you produce an effective plot?
- [tibble accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md): (9%)
	- does your tibble reflect the task?

-----

Pick three of the six tasks below, and produce: 

- a tibble, using `dplyr` as your data manipulation tool;
- an accompanying plot of data from the tibble, using `ggplot2` as your visualization tool; and
- some dialogue about what your tables/figures show (doesn't have to be much).

Or, make up your own task(s)! If you want to do something comparable but different, i.e. swap one quantitative variable for another, be my guest! If you are feeling inspired and curious, then we're doing this right. Go for it. Just write down the task that you are now doing. Between the dplyr coverage in class and the list below, I think you get the idea.

Relax about the following things:

- Your figure does not have to depict every single number from the data aggregation result. Use your judgement. It just needs to complement the table, add context, and allow for some sanity checking both ways.
- Tidying/reshaping is NOT your assignment. Many of your tables will be awkwardly shaped in the report. That's OK.
- Table beauty is not a big deal. Simply printing to "screen" is fine. 

Tip: Treat this assignment as a "cheat sheet" for future-you! Don't assume that you'll remember the lessons you learned while writing this assignment. Write things down:

- Add notes on difficulties/oddities you encountered. For example, which figures are easy/hard to make, which data formats make better inputs for plotting functions vs. for human-friendly tables.
- Provide attribution whenever you take code or an idea from somewhere else, whether a blog post, a colleague, a vignette, etc. Putting those pointers in your "cheat sheet" will be useful for future-you -- and it's just good practice to indicate where you got things from.


### Task Option 1

Report the absolute and/or relative abundance of countries with low life expectancy over time by continent: Compute some measure of worldwide life expectancy – you decide – a mean or median or some other quantile or perhaps your current age. Then determine how many countries on each continent have a life expectancy less than this benchmark, for each year.

### Task Option 2

Get the maximum and minimum of GDP per capita for all continents.

### Task Option 3

Look at the spread of GDP per capita within the continents.

### Task Option 4

Compute a trimmed mean of life expectancy for different years. Or a weighted mean, weighting by population. Just try something other than the plain vanilla mean.

### Task Option 5

How is life expectancy changing over time on different continents?

### Task Option 6

Find countries with interesting stories. Open-ended and, therefore, hard. Promising but unsuccessful attempts are encouraged. This will generate interesting questions to follow up on in class.


## Optional Exercise (2%)

Get table and figure side-by-side. [This gist](https://gist.github.com/jennybc/e9e9aba6ba18c72cec26) might get you started.
