---
title: "milestone_03"
author: "Firas Moosvi"
date: "Updated `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this milestone, you will address feedback from TAs about milestone2, **finalize** your analysis, and produce a final parameterized report.

## Expectations
- You should be committing to git every time you work on this project.
- git commit messages should be meaningful. These will be marked. It's OK if one or two are less meaningful, but most should be.
- After the repository is set-up, each group member should fork the repository to their personal GitHub.com account and work there, and send pull-requests of their work to the upstream repo (the one they forked). The other team mate should review, critique (if necessary) and finally accept their team mates pull request.
  - See below for "how to catch up to a forked repo if there are changes upstream".
- Use GitHub issues to communicate to their team mate (as opposed to email or Slack)
- Your question, analysis and visualization should make sense. It doesn't have to be complicated.
- You should use proper grammar and full sentences in your README. Point form may occur, but should be less than 10% of your written documents.
- You **must** include the URL of your report in the `README.md` file of your project repo so we can easily view it.
- Create a release on your project repo named `milestoneX` and submit that URL on Canvas for us to grade.
- Your report should be knitted and rendered as an HTML or PDF file as described [here](https://stat545.stat.ubc.ca/evaluation/assignments/).
  - Here is an example of the URL we are expecting for each milestone: https://github.com/STAT547-UBC-2019-20/demo_project/tree/milestoneX
  
### Folder structre

- `docs`: Move your Rmd files here, include your final report.
- `data`: All your data should be saved to this directory. Also, if you re-save your data after cleaning/wrangling, it should be saved as a new file here.
- `scripts` (or `src`): move all your scripts here. This directory should only contain scripts
- `images`: your scripts should export images to this directory, also include any images needed for your report
- `tests`: You may (optionally) add some tests to your functions and scripts in separate test files. See [this section](https://stat545guidebook.netlify.com/functional-programming-in-r-part-ii.html#how-should-i-organize-my-tests) from class notes that describes how to add tests to your scripts. 

## Mechanics (5%)

Follow the instructions for making a tidy submission, found on the [assignments home page](https://stat545.stat.ubc.ca/evaluation/assignments).

If there's any further uncertainty in determining a grade for this "mechanics" portion, the [UBC MDS mechanics rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_mech.md) will be referred to.

## Writing (10%)

- You must use proper English, spelling, and grammar.
- You should write concisely. 
- If there's any further uncertainty in determining a grade here, the [UBC MDS writing rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_writing.md) will be used.

## **Task 1. Perform your linear regression in a new script** (20%)

At this point you should be ready to do your linear regression!
If you need a refresher on how to do a linear regression, [here](https://cran.r-project.org/web/packages/broom/vignettes/broom.html) is the documentation, and [here](https://cfss.uchicago.edu/notes/linear-models/) is a lengthier and more in-depth demo.

Here are some guidelines:

- You should create a new script and put it in your `scripts` directory
- This script should do your linear regression, and any subsequent explorations and analyses you choose to do
- Export any plots you want to include in your final report as an image (to the `images` directory)
- Export your `model` object to an `RDS` file so you can load this file in your final report and use the `tidy`, `augment`, or `glance` functions from the `broom` package to reference the model's statistical findings
- Don't forget to add a line in the Usage section on how to use this script

## **Task 2: Complete your final report and knit it using a script** (15%)

Write a final script that knits your DRAFT of your final report (an Rmarkdown file) to an HTML and PDF file.

Your script should:

- Live in the `scripts` directory
- Knit the final report Rmd file so that it exports an HTML and PDF file.
- Run without any intervention from the user after running the script from a terminal/command prompt
- Print a helpful message to the terminal informing the user that the script has completed successfully

Guidelines for your final project:

- Be written in Rmarkdown and should not have any "hard-coded" numbers and values
  - Use r code chunks or inline r code)
  - Load an RDS file from your analysis script and report the relevant results of the statistical analysis
- Have an introduction/motivation and description of research question
- Have a section describing your dataset (EDA); make sure you import pngs from the `images` directory rather than creating them again!
- Have a section for your analysis methods (linear regression)
- Have a section for your results
- Have a section for your discussion/conclusion
- You can liberally borrow from your `milestone1` EDA, particularly the introduction/motivation
  
## **Task 3. Automate your pipeline with MAKE** (40%)

Write another script, a Makefile (literally called `Makefile`), to act as a driver script to rule them all. 
This script should run the others in sequence, specifying filenames, paths, and other neccessary commandline arguments.

This script should:

  - live in the project's root directory and be named `Makefile`
  - be well documented (using the project README and comments inside the Makefile to explain what each section does and how to use it)
  - have an `all:` target so that you can easily run the entire analysis from top to bottom by running `make all` at the command line
  - have a `clean:` target so that you can easily "undo" your analysis by running `make clean` at the command line

## **Task 4: Instructions to reproduce your analysis ** (10%)

Your final task for this milestone is to add a **USAGE** section in your project README so someone can completely reproduce your analysis from start to finish.
This section should have two subsections, one for running the analysis using GNU MAKE, and the other for running each script individually.
You should also list all packages and dependencies required for your project.
What level of reproducibility should you expect?
Well, imagine if someone clones your repository, deletes all the files in every directory except your README, the `scripts` and `docs` directory - could they follow both sets of instructions in the USAGE section to reproduce your final report?

### Usage instructions for running scripts individually

- This section should largely be the same as what you had in `milestone_02`, just updated if your scripts changed.
- It's a good idea to provide instructions for running each script individually in case people do not have MAKE installed on their systems and want to reproduce your analyses.
- **IMPORTANT**: You should make sure this section is complete and correct ASAP so your classmates that are reviewing your project are able to run your analysis.

### Usage instructions for GNU MAKE

- All possible options for your `Makefile` (`make clean`, `make all`, etc...) should be well documented using both the project README and comments inside the Makefile to explain what each section does and how to use it.

## [OPTIONAL/BONUS] Task 5. Add tests to your scripts

[This section](https://stat545guidebook.netlify.com/functional-programming-in-r-part-ii.html#how-should-i-organize-my-tests) from class notes that describes how to add tests to your scripts. 
You are encouraged to consider adding some tests to your project (either in the `tests` directory or as individual tests inside your scripts).
You may receive up to 30% as a bonus on this milestone_03 if you add good tests to your project scripts.

<!-- 
## Example of final product

One of your TAs (Matthew) has prepared an example of what we are expecting for this milestone.
We will release this to you after Thursday's lecture and you will be able to find it [here](https://github.com/STAT547-UBC-2019-20/demo_project/tree/milestone2).
-->