---
title: "STAT 545 Navigation Dashboard"
output: html_document
---

```{r, message = FALSE, warning = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
source(here::here("content", "dates-2022.R"))
```

Use this page to navigate your way through STAT 545.

This page was last updated on `r format(Sys.Date(), "%a, %b %d")`.

# Slack

Slack channel specifically for students: <https://stat545classroom2022.slack.com/>

-   Be sure to be part of the `#announcements` channel to receive official course announcements!
-   Please do not send private questions to individual TA's -- use the `#general` channel instead.
-   Slack communication guidelines here: <https://stat545.stat.ubc.ca/slack_communication/>

# Topics

### Part A

| Date                                      | Topic                                            | Worksheet / to do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|-------------------------------------------|--------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `r format(dates_545a[1] , "%a, %b %d")`   | **NO CLASS** (IMAGINE DAY)                       | **Check what you have to install for this class in [Thursday's notes](/notes/notes-a01).** We will set aside some time on Thursday for installation, but if you have a lot to install, then we **STRONGLY SUGGEST** that you start trying to install the needed tools before class. Also see [advice on getting unstuck](/notes/notes-a00).                                                                                                                                                                                                                                                                                                                                                                                                     |
| `r format(dates_545a[1+1] , "%a, %b %d")` | [Intro to STAT 545 and R](/notes/notes-a01)      | Worksheet A1 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a01.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a01.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a01.ipynb.zip)) (practice worksheet, not for marks); also, see installation instructions in the notes. Worksheet A1 solutions ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a01_solutions.ipynb).; [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a01_solutions.ipynb)) |
| `r format(dates_545a[2+1] , "%a, %b %d")` | [Version Control](/notes/notes-a02)              | NA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `r format(dates_545a[3+1] , "%a, %b %d")` | [Authoring](/notes/notes-a03)                    | NA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| `r format(dates_545a[4+1] , "%a, %b %d")` | [Data Manipulation with dplyr](/notes/notes-a04) | Worksheet A2 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a02.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a02.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a02.ipynb.zip)) (Due Wednesday Sept. 28, 2022 at 17:00 PT)                                                                                                                                                                                                                                                                                                                                  |
| `r format(dates_545a[5+1] , "%a, %b %d")` | (Data Manipulation with dplyr, continued)        | Worksheet A2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| `r format(dates_545a[6+1] , "%a, %b %d")` | [Graphing](/notes/notes-a06)                     | Worksheet A3 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a03.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a03.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a03.ipynb.zip)) (Due Friday, Oct 7, 2022 at 17:00 PT)                                                                                                                                                                                                                                                                                                                                       |
| `r format(dates_545a[7+1] , "%a, %b %d")` | (Graphing, continued)                            | Worksheet A3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| `r format(dates_545a[8+1] , "%a, %b %d")` | [Tidy Data](/notes/notes-a08)                    | Worksheet A4 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a04.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a04.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a04.ipynb.zip)) (Due Friday, Oct 14, 2022 at 17:00 PT)                                                                                                                                                                                                                                                                                                                                      |
| `r format(dates_545a[9+1] , "%a, %b %d")` | [Model Fitting](/notes/notes-a09)                | Worksheet A4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| `r format(dates_545a[10+1], "%a, %b %d")` | [Factors and Dates](/notes/notes-a10)            | Worksheet A5 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a05.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a05.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a05.ipynb.zip)) (Due Friday, Oct 21, 2022 at 17:00 PT)                                                                                                                                                                                                                                                                                                                                      |
| `r format(dates_545a[11+1], "%a, %b %d")` | [Tibble joins](/notes/notes-a11)                 | Worksheet A5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| `r format(dates_545a[12+1], "%a, %b %d")` | [Reading and Writing Data](/notes/notes-a12)     | Worksheet A6 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a06.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a06.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a06.ipynb.zip)) (Due Wednesday, Oct 26, 2022 at 17:00 PT)                                                                                                                                                                                                                                                                                                                                   |
| `r format(dates_545a[13+1], "%a, %b %d")` | Overflow or TBA                                  | NA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

# Worksheets

Options for working on these worksheets:

-   Edit them with instances of jupyterlab or jupyter notebook that are installed on your own computer. (BEST)
-   Edit them with UBC Syzygy (pronounced sizz-ij-ee): <https://ubc.syzygy.ca/>
-   Edit them with Google Colab: <https://research.google.com/colaboratory/> (LEAST PREFERABLE)

*Submit the worksheets by uploading your .ipynb file to the corresponding canvas assignment slot*.

*To get full marks for each participation worksheet, you must successfully answer at least 50% of all autograded questions.*

### Part A

| Worksheet    | Download                                                                                                               | View                                                                                                                    | Zip file                                                                                                              | \# required questions | Deadline                                                                                                                                                                                                                                                                                                 |
|--------------|------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|-----------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Worksheet A1 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a01.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a01.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a01.ipynb.zip) | NA                    | **not for submission.** Solutions ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a01_solutions.ipynb), [view it on Github](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a01_solutions.ipynb)). |
| Worksheet A2 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a02.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a02.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a02.ipynb.zip) | 10                    | **Wednesday, September 28, 2022 at 17:00 PT**                                                                                                                                                                                                                                                            |
| Worksheet A3 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a03.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a03.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a03.ipynb.zip) | 10                    | **Friday, Oct 7, 2022 at 17:00 PT**                                                                                                                                                                                                                                                                    |
| Worksheet A4 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a04.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a04.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a04.ipynb.zip) | 10                    | **Friday, Oct 14, 2022 at 17:00 PT**                                                                                                                                                                                                                                                                   |
| Worksheet A5 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a05.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a05.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a05.ipynb.zip) | 10                    | **Friday, Oct 21, 2022 at 17:00 PT**                                                                                                                                                                                                                                                                   |
| Worksheet A6 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a06.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a06.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a06.ipynb.zip) | 10                    | **Wednesday, Oct 26, 2022 at 17:00 PT**                                                                                                                                                                                                                                                                  |

```{=html}
<!--
### Part B

| Date                                    | Topic                                                                | Worksheet                                                                                                                                                                                                                                                                                                                                                                                                     |
|-----------------------------------------|----------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `r format(dates_545b[1] , "%a, %b %d")` | [Functions](/notes/notes-b01)                                        | Worksheet B1 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_b01.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_b01.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_b01.ipynb.zip)) (Due Wednesday, November 2nd at 17:00 PT) |
| `r format(dates_545b[2] , "%a, %b %d")` | Functions (cont'd)                                                   | Worksheet B1                                                                                                                                                                                                                                                                                                                                                                                                  |
| `r format(dates_545b[3] , "%a, %b %d")` | [Dashboards](/notes/notes-b02)                                       | NA                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r format(dates_545b[4] , "%a, %b %d")` | Dashboards (cont'd)                                                  | NA                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r format(dates_545b[5] , "%a, %b %d")` | [Automation](/notes/notes-b03) (**Optional** lecture)                | NA                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r format(dates_545b[6] , "%a, %b %d")` | University closed (mid-term break / Remembrance Day)                 | NA                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r format(dates_545b[7] , "%a, %b %d")` | [R packages](/notes/notes-b04)                                       | NA                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r format(dates_545b[8] , "%a, %b %d")` | R packages, Part 2                                                   | NA                                                                                                                                                                                                                                                                                                                                                                                                            |
| `r format(dates_545b[9] , "%a, %b %d")` | [Character data](/notes/notes-b05)                                   | Worksheet B2 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_b02.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_b02.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_b02.ipynb.zip)) (Due Friday November 25th at 17:00 PT)    |
| `r format(dates_545b[10], "%a, %b %d")` | [List columns](/notes/notes-b06)                                     | Worksheet B3 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_b03.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_b03.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_b03.ipynb.zip)) (Due Friday December 2nd at 17:00 PT)     |
| `r format(dates_545b[11], "%a, %b %d")` | List columns, cont'd                                                 | Worksheet B3                                                                                                                                                                                                                                                                                                                                                                                                  |
| `r format(dates_545b[12], "%a, %b %d")` | List columns, cont'd                                                 | Worksheet B3                                                                                                                                                                                                                                                                                                                                                                                                  |
| `r format(dates_545b[13], "%a, %b %d")` | [Blogdown](/notes/notes-b07) (**Optional** lecture); plus automation | NA                                                                                                                                                                                                                                                                                                                                                                                                           
```
```{=html}
<!--
### Part B

| Worksheet    | Download                                                                                                               | View                                                                                                                    | Zip file                                                                                                              | \# required questions | Deadline                                    |
|--------------|------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|-----------------------|---------------------------------------------|
| Worksheet B1 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_b01.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_b01.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_b01.ipynb.zip) | 10                    | **Wednesday, November 2, 2022 at 17:00 PT** |
| Worksheet B2 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_b02.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_b02.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_b02.ipynb.zip) | 10                    | **Friday, November 25, 2022 at 17:00 PT**   |
| Worksheet B3 | [.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_b03.ipynb) | [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_b03.ipynb) | [Download zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_b03.ipynb.zip) | 10                    | **Friday, December 02, 2022 at 17:00 PT**   |
-->
```
# Projects

You will be working on various projects on GitHub repositories within a GitHub Organization setup for this course. Some general things you should know:

**How to followup with a project submission**

You'll be given feedback as an Issue in your project repository, sometimes before your grade is posted.

-   Make sure you're `Watch`ing your repository, so that you will be notified by email whenever a new Issue or comment is posted -- you can find this option in the upper-right hand corner of your repository page.
-   You can use the Issue thread to have a conversation about your assignment results.
-   If you would like to dispute your grade, this Issue thread is the place to do it, but please do so only within 1 week after the grade has been posted.

## Collaborative Project (Part A)

There are two milestones, each equally weighted:

-   [Milestone 1](/collaborative-project/milestone1/): Due **Friday, September 23, 2022 at 17:00 PT**.
-   [Milestone 2](/collaborative-project/milestone2/): Due **Friday, September 30, 2022 at 17:00 PT**.

## Mini-Data Analysis (Part A)

There are two milestones, each equally weighted:

-   [Milestone 1](/mini-project/mini-project-1/): Due **Wednesday, October 12, 2022 at 17:00 PT**.
-   [Milestone 2](/mini-project/mini-project-2/): Due **Friday, October 28, 2022 at 17:00 PT**.

```{=html}
<!--## Assignments (Part B)

There are four assignments, each equally weighted:

-   [Assignment B-1](/assignments/assignment-b1): Due **Friday, November 04, 2022 at 17:00 PT**.
-   [Assignment B-2](/assignments/assignment-b2): Due **Friday, November 18, 2022 at 17:00 PT**.
-   [Assignment B-3](/assignments/assignment-b3): Due **Friday, November 25, 2022 at 17:00 PT**.
-   [Assignment B-4](/assignments/assignment-b4): Due **Friday, December 2, 2022 at 17:00 PT**.
-->
```
