---
title: "Lecture Notes: "
subtitle: "Version 1.0.0"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
knitr::opts_chunk$set(fig.width = 5, fig.height = 3, 
                      fig.align = "center", error = TRUE)
```


## Learning Objectives


## Parallel Resources

This topic parallels the following resources. Take about 30 minutes to get acquainted with the following before coming to class:

- 

I suggest referring to this material when engaging with today's topic.

## Additional Resources



## Quiz



## Demonstration



-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: More R, and a tour of other things

```{r thurs-date}
cat(thurs_date_pretty)
```

By the end of this class, we will cover as much of the following as we can:

- More R Basics:
  - vectors and lists
  - Make a reproducible example using the `reprex` package.
  - Use of {}.
  - attributes
  - style guides
- Turning your GitHub repository into a Website
- Turning your Rmd into a presentation (2 min)

These three topics were the top three chosen in the poll.

| Lecture | Demonstration | View |
|---------|-----------|------|
| 13-A: Choose your adventure | [.Rmd](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/demonstrations/demo13a-misc.Rmd) | [Knitted demo](/demonstrations/demo13a-misc) |

#### Prepare for Class

Before class:

- Watch the STAT 545 Video Series: Class `r thurs_class_num` (to be posted)

Some useful (but not mandatory) resources are:

- The book [Advanced R](https://adv-r.hadley.nz/) is an approachable, free, online book for learning more about R.
  - [Vectors chapter](https://adv-r.hadley.nz/vectors-chap.html) for vectors and lists. 
  - [Subsetting chapter](https://adv-r.hadley.nz/subsetting.html) for subsetting vectors.
  - [Functions chapter](https://adv-r.hadley.nz/functions.html)
  - [Environments chapter](https://adv-r.hadley.nz/environments.html)
  - [S3 chapter](https://adv-r.hadley.nz/s3.html)

#### During Class

- In-class demo of more R things, and a tour of other topics.
- **No quiz**

-----