---
title: "Lecture Notes: Character Data, and Choose Your Adventure"
subtitle: "**Development** Version 0.0.0.9000"
output: html_document
---


## Learning Objectives

From today's class, students are anticipated to be able to:




## Prepare for Class

Read/watch one of the following two resources before class:

- Watch STAT 545 Episode
- 

## Resources

## Outline

- [Strings Worksheet 2018](https://github.com/UBC-STAT/stat-545-guidebook/blob/pre-leave/tutorials/cm102-exercise.Rmd)
- multivariate pivoting? (>2)

Ideas for choose-your-adventure:

- Continuous Integration (with Travis? GitHub Actions?)
- docker (or just in general, environment management)
- Cloud computing
- bookdown, for writing a thesis?
- blogdown, for making a website? This might be a stretch -- not really related to data analysis.
- organizing an analysis into multiple files
- Making a github pages site, 
- using blogdown, 
- making presentation slides,
- making a bookdown book, 
- adding citations to markdown, 
- numbering and referencing sections in an Rmd, 
- shiny in an Rmd,