---
title: "Week 3-B Lecture Notes: R Packages for Data Analysis"
subtitle: "**Development** Version 0.9000"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 10  # 1 through 14
#-------------
source(here::here("content", "dates.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec0 + days((week_num - 1) * 7)
thurs_date <- tues_date + days(2)
```


```{r tues-date}
cat(format(tues_date, "%A, %b %d"), "-", 
    format(thurs_date, "%A, %b %d"))
```

## Learning Objectives

From today's class, students are anticipated to be able to:




## Prepare for Class

Read/watch one of the following two resources before class:

- Watch STAT 545 Episode
- 

## Resources



## Outline


- [Guidebook 2018](https://github.com/UBC-STAT/stat-545-guidebook/blob/master/cm205.Rmd)
- [Firas Guidebook](https://github.com/UBC-STAT/stat-545-guidebook/blob/master/cm112.Rmd)