---
title: "Lecture Notes: Automation"
subtitle: "**Development** Version 0.9000"
output: html_document
---


## Learning Objectives

From today's class, students are anticipated to be able to:




## Prepare for Class

Read/watch one of the following two resources before class:

- Watch STAT 545 Episode
- 

## Resources

- Useful resources: https://www.r-bloggers.com/long-running-r-commands-unix-screen-nohup-and-r/ and https://stackoverflow.com/questions/53486153/how-to-write-console-output-to-a-text-file-with-rscript-like-you-can-with-r-cmd


## Outline

- The case for non-interactive programming; philosophy behind a multi-file analysis. Notion of an "instance" of R. 
- How to run interactively vs. from source:
  - Rmd: run interactively by just executing the cells; from source = knit.
  - R script: interactive = just execute code (moves it to console); from source = "render report" or `source()`.
  - Then move on to bash
- Crash course on the command line (bash; zsh).
- running R scripts in the background. "jobs".
  - The idea behind cloud computing: run code non-interactively from a server. Need to make sure software is installed: docker. 
- `source()` for reading in a particular R script.
- makefiles for running parts of an analysis, or the whole thing. 
- Draw from my recent analysis

Draw from 

- [Guidebook 2018](https://github.com/UBC-STAT/stat-545-guidebook/blob/master/cm209.Rmd)
- [Examples from 2018](https://github.com/UBC-STAT/stat-545-guidebook/blob/pre-leave/tutorials/cm109-automation_examples.zip)