---
title: "Office Hours"
date: "Updated `r Sys.Date()`"
---

```{r, echo = FALSE, warning = FALSE}
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
```

Want to talk about the course outside of lecture? Let's talk during these dedicated times. You're always welcome to schedule one-off meetings with us, too.

## STAT 545A

```{r, echo = FALSE, results='asis'}
oo545 <- suppressMessages(read_csv(here::here("content", "officehours-545a.csv")))
oo545 %>% 
	mutate(Date = dmy(Date),
		   Day  = wday(Date, label = TRUE)) %>% 
  select(Person,Date,Time) %>%
#	select(Person, Day, Date, Time, Place) %>% 
	arrange(Date, Time) %>% 
	# DT::datatable()
	kable()
```
<!--
## STAT 547M
-->
```{r, eval = FALSE, echo = FALSE, results='asis'}
oo547 <- suppressMessages(read_csv(here("content", "officehours-547m.csv")))
kable(oo547)
```