---
title: "Policies"
date: "Updated `r Sys.Date()`"
---

In addition to [UBC's Campus-wide Policies and Regulations](http://www.calendar.ubc.ca/vancouver/?tree=3,0,0,0), STAT 545A and STAT 547M adopt the following policies.

## Auditing Students

Auditing students will be:

1. Graded on a Pass/Fail basis for each assignment/course activity
2. Exempted from the peer review portion of the course
3. Doing the team project as an individual project (with no other change in scope or requirements)

If you would like to audit the course, you must submit the request by 11:59 PM on Thursday March 5th, 2020. After this - without exceptions - students will not be permitted to switch to (or from) audit status.

Auditing students are expected to complete all assessments. The difference between enrolling for credit is that auditing students are graded on each assignment on a pass/fail basis. To switch to audit status (or from audit to regular enrolment), please contact gradinfo@stat.ubc.ca. 

## Late Policy

In STAT 547, I have added a 48-hour grace period for all submissions - this means that should "life happen" and you're unable to submit by the deadline, you will still be able to submit your assignments for full credit up to 48 hours after the due date has passed. 
You do not need to inform the teaching team if you need to use the grace period. 
After the 48 hour grace period, solutions will be released and no submissions will be accepted - no exceptions.

## Academic Concession

UBC no longer requires a doctor's note (or supporting documentation) for [academic concession](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,48,0,0). A self-declaration will suffice -- [here](/concession_template.pdf) is a template you can use. Please submit this to the instructor directly via email. 

For STAT 545A and 547M, a "conflicting responsibility" includes needing to travel for a conference or field work.

## Plagiarism

Plagiarism, which is intellectual theft, occurs where an individual submits or presents the oral or written work of another person as his or her own and can include:

- multiple students submitting the same response
- copying from sources without citing them
- copying verbatim (word-for-word) from source and citing, but failing to make it explicit that this is a quotation (quotations should be used only rarely, if at all)

Plagiarism will not be tolerated in the MDS program and may result in dismissal from the program. Students are responsible for ensuring that any work submitted does not constitute plagiarism. Students who are in any doubt as to what constitutes plagiarism should consult their Instructor before handing in any assignments.

For more information see the [UBC Academic Misconduct policies](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,54,111,959).

#### Code Plagiarism

Students must correctly cite any code that has been authored by someone else or by the student themselves for other assignments. Cases of code plagiarism may include, but are not limited to:

- the reproduction (copying and pasting) of code with none or minimal reformatting (e.g., changing the name of the variables)
- the translation of an algorithm or a script from a language to another
- the generation of code by automatic code-generations software

An “adequate acknowledgement” requires a detailed identification of the (parts of the) code reused and a full citation of the original source code that has been reused.

## UBC's Policies and Resources to Support Student Success

UBC provides resources to support student learning and to maintain healthy lifestyles but recognizes that sometimes crises arise and so there are additional resources to access including those for survivors of sexual violence. UBC values respect for the person and ideas of all members of the academic community. Harassment and discrimination are not tolerated nor is suppression of academic freedom. UBC provides appropriate accommodation for students with disabilities and for religious, spiritual and cultural observances. UBC values academic honesty and students ae expected to acknowledge the ideas generated by others and to uphold the highest academic standards in all of their actions. Details of the policies and how to access support are available [here](https://senate.ubc.ca/policies-resources-support-student-success).
