---
title: "Resources"
---

Here are some great resources to learn about the topics covered in STAT 545A and STAT 547M.

### [R for Data Science](http://r4ds.had.co.nz/) (aka "r4ds")
__Garrett Grolemund, Hadley Wickham__

Closely mirrors the topics of this course, especially STAT 545A, making this book a good alternative to the main textbook for the course.

### [Happy git with R and RStudio](https://happygitwithr.com)
__Jenny Bryan, the STAT 545 TAs, Jim Hester__

Helps you set up some key tools we'll be using for the course. 

### [What They Forgot to Teach You About R](https://whattheyforgot.org/)
__Jennifer Bryan, Jim Hester__

A work-in-progress, this book helps you use R responsibly for data analysis. 

### [Advanced R](http://adv-r.had.co.nz/)
__Hadley Wickham__

If you want to learn more about R as a programming language, this is a very readable and concise way of doing so.

### [ggplot2 book](http://webcat2.library.ubc.ca/vwebv/holdingsInfo?bibId=8489511)
__Hadley Wickham__

Useful for digging deeper into `ggplot2`.

### [RMarkdown book](https://bookdown.org/yihui/rmarkdown/)
__Yihui Xie, J. J. Allaire, Garrett Grolemund__

Comprehensive resource for everything R Markdown related. 

### [R packages](http://r-pkgs.had.co.nz/)
__Hadley Wickham__

Readable, approachable help for making R packages.
