---
title: "Class Meeting Schedule"
date: "Updated `r Sys.Date()`"
---

Here are the topics for each class meeting. You can find the notes on the navigation bar above. 

Be sure to Bring a laptop to every class!

There will always be two TA's in class to help students with the live coding exercises. 

## STAT 545A

| Meeting No.         | Date         | Topic | 
|---------------------|--------------|-------|
| 01 | sep-03 tues    | Intro to course and software |
| 02 | sep-05 thurs   | Markdown and GitHub |
| 03 | sep-10 tues    | Getting familiar with R & RMarkdown |
| 04 | sep-12 thurs   | The git workflow; collab with GitHub |
| 05 | sep-17 tues    | working with data in R; <br> `dplyr` and the `tidyverse` |
| 06 | sep-19 thurs   | ggplot2, Part I |
| 07 | sep-24 tues    | ggplot2, Part II |
| 08 | sep-26 thurs   | Grouping of tibbles |
| 09 | oct-01 tues    | Tidy data, reshaping |
| 10 | oct-03 thurs   | Guest Lecture: Rashedul, on table joins |
| 11 | oct-08 tues    | Advanced R programming; file I/O |
| 12 | oct-10 thurs   | The joy of Factors |
| 13 | oct-15 tues    | Revisit ggplot; plotly; <br> practicalities of daily figure-making |
| 14 | oct-17 thurs   | The model-fitting paradigm in R; `broom`; <br> deep thoughts about data analytic work |

## STAT 547M

Subject to change!

| Meeting No.         | Date         | Topic | 
|---------------------|--------------|-------|
| 01 | feb-25 tues    | Writing your own R functions |
| 02 | feb-27 thurs   | Regular expressions and character data |
| 03 | mar-03 tues    | purrr, list-columns, nested data frames: Part I |
| 04 | mar-05 thurs   | purrr, list-columns, nested data frames: Part II |
| 05 | mar-10 tues    | Build your first R package: Part I |
| 06 | mar-12 thurs   | Build your first R package: Part II |
| 07 | mar-17 tues    | shiny apps, and related tools: Part I |
| 08 | mar-19 thurs   | shiny apps, and related tools: Part II |
| 09 | mar-24 tues    | Automate tasks and pipelines: Part I |
| 10 | mar-26 thurs   | Automate tasks and pipelines: Part II |
| 11 | mar-31 tues    | Get data from the web: Part I |
| 12 | apr-02 thurs   | Get data from the web: Part II |