---
title: "STAT 545A: Week 6A"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 6  # 1 through 14
#-------------
source(here::here("content", "dates.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec0 + ddays((week_num - 1) * 7)
tues_date_pretty <- paste0(
  month(tues_date, label = TRUE), " ", 
  day(tues_date), ", ", 
  year(tues_date)
)
wed_date <- tues_date + ddays(1)
wed_date_pretty <- paste0(
  month(wed_date, label = TRUE), " ", 
  day(wed_date), ", ", 
  year(wed_date)
)
thurs_class_num <- paste0(str_pad(week_num * 2 - 2 + 1, width = 2, pad = 0), letter)
thurs_date <- tues_date + ddays(2)
thurs_date_pretty <- paste0(
  month(thurs_date, label = TRUE), " ", 
  day(thurs_date), ", ", 
  year(thurs_date)
)
fri_date <- tues_date + ddays(3)
fri_date_pretty <- paste0(
  month(fri_date, label = TRUE), " ", 
  day(fri_date), ", ", 
  year(fri_date))
  sat_date <- tues_date + ddays(4)
sat_date_pretty <- paste0(
  month(sat_date, label = TRUE), " ", 
  day(sat_date), ", ", 
  year(sat_date)
)

```

-----

<!-- ******WORKSHEET****** -->

## Worksheet `r paste0(week_num - 1, letter)`

**Due:** Friday, `r fri_date_pretty` at 23:59 PST

-----

----- 

<!-- ******TUESDAY'S CLASS****** -->

## Tuesday's Class `r tues_class_num`: Special Data Types-Factors and Dates

```{r tues-date}
cat(tues_date_pretty)
```

From today's class, students are anticipated to be able to:

- Recognize what the factor class is 
- Convert data in a dataframe to factors
- Use the tsibble package to convert to various date formats
- Plot with factors
- Reorder levels within factors


#### Prepare for Class
- Watch the STAT 545 Video Series: Class `r tues_class_num`
- Read the [forcats](https://forcats.tidyverse.org) package page and reference guide on page. 
- Read the `tsibble` [vignette](https://cran.rstudio.com/web/packages/tsibble/vignettes/intro-tsibble.html)

Some useful (but not mandatory) readings are:
* Jenny Bryan's notes on [factors](https://stat545.com/factors-boss.html)

#### During Class

- In class demo, covering:
  - Converting data to factor types and defining levels
  - Plotting with factors
  - Changing order of levels
  - Recoding factors
  - Recoding data into dates using tsibble

- Quiz
  - **Complete the Class `r tues_class_num` Quiz on Canvas by Wednesday, `r wed_date_pretty` at 11:00am PST.**

-----

-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: Tibble Joins

```{r thurs-date}
cat(thurs_date_pretty)
```

From today's class, students are anticipated to be able to:

- Recognize how to manipulate data through a variety of tibble joins such as:
  - left_join
  - right_join
  - full_join
  - anti_join
- Perform set operations on data
- 
#### Prepare for Class

- Watch the [STAT 545 Video Series: Class `r thurs_class_num`](https://youtu.be/TTNfLtEUFDQ)
- Read the "two-table verbs"'s [vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html)

Some useful (but not mandatory) readings are:

-  [Jenny's Join Cheatsheet](https://stat545.com/join-cheatsheet.html) for a quick reference to joins.
- [Relational Data chapter](https://r4ds.had.co.nz/relational-data.html) in "R for Data Science".
- [dplyr cheatsheet](https://rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

#### During Class

- In class demo, covering:
- [__Mutating joins__](https://r4ds.had.co.nz/relational-data.html#mutating-joins) add new columns to the "original" tibble.
- [__Filtering joins__](https://r4ds.had.co.nz/relational-data.html#filtering-joins) filter the "original" tibble's rows.
- [__Set operations__](https://r4ds.had.co.nz/relational-data.html#set-operations) work as if each row is an element in a set. 
- __Binding__ stacks tables on top of or beside each other, with `bind_rows()` and `bind_cols()`.

- Quiz
 **Complete the Class `r thurs_class_num` Quiz on Canvas by Friday, `r fri_date_pretty` at 11:00am PST.**
-----

## Thursday Office Hours from 16:00 - 17:00 PST:

Join Almas for office hours regarding this week's content, the milestones or other questions about R. Can't come to office hours, reach out on Slack/Canvas/Email. 

-----

<!-- ******PROJECT****** -->

## Collobarative Milestone 3 

**Due:** Saturday, `r sat_date_pretty` at 23:59 PST

-----
