---
title: "STAT 545A: Week 2"
output: html_document
---


  

```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 2  # 1 through 14
#-------------
source(here::here("content", "dates.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec0 + ddays((week_num - 1) * 7)
tues_date_pretty <- paste0(
  month(tues_date, label = TRUE), " ", 
  day(tues_date), ", ", 
  year(tues_date)
)
thurs_class_num <- paste0(str_pad(week_num * 2 - 2 + 1, width = 2, pad = 0), letter)
thurs_date <- tues_date + ddays(2)
thurs_date_pretty <- paste0(
  month(thurs_date, label = TRUE), " ", 
  day(thurs_date), ", ", 
  year(thurs_date)
)
fri_date <- tues_date + ddays(3)
fri_date_pretty <- paste0(
  month(fri_date, label = TRUE), " ", 
  day(fri_date), ", ", 
  year(fri_date)
)
```


----- 

<!-- ******TUESDAY'S CLASS****** -->

## Tuesday's Class `r tues_class_num`: Collaboration with git and GitHub

```{r tues-date}
cat(tues_date_pretty)
```

From today's class, students are anticipated to be able to:

- use git on their own computer (locally)
- connect between a local git repository and that repository on GitHub, using RStudio
- make commits in git using RStudio
- make a branch in git using RStudio or GitHub
- use collaborative GitHub features such as Issues and pull requests.

#### Prepare for Class

Take about 30 minutes to get acquainted with the following before coming to class:

- Watch [STAT 545 Episode 2-A: Git and GitHub for an Organized Project](https://youtu.be/l2ftm-YwJs8) (a copy is also available on Canvas)
- Read about the basic version control workflow (without branching) at [Happy git w R: Chapter 20](https://happygitwithr.com/git-basics.html).
- Read the [Understanding the GitHub flow](https://guides.github.com/introduction/flow/) to get a sense of branching.


#### During Class

Rough schedule:

| Time period | Activity |
|-------------|----------|
| 09:30 - 10:00 | Vincenzo demonstrates version control and GitHub |
| 10:00 - 10:10 | Quiz discussion (see below) with think-pair-broadcast activity. |
| 10:10 - 10:15 | Break |
| 10:10 - 11:00 | Students work on their Collaborative Project Milestone 1, especially __Making/joining your project repo__ and __creating a teamwork document__. |

Complete the __Class 2-A Quiz__ on canvas __by Wednesday, September 16 at 11:00am PST__. Questions:

1. You've just successfully pushed your branch to GitHub! True or False: it's still possible for the branch on GitHub to contain work that's not on your computer.
2. You're ready to push some code you added to `code.R` to GitHub, but just found out that your teammate completely changed `code.R` on GitHub! True or False: If you pull the repository from GitHub, you'll get an error because your `code.R` conflicts with GitHub's `code.R`. 
3. True or False: If you've just changed a file on your computer, in order to push it to GitHub, you'll first need to commit the file. 

Group of answer choices


#### Useful Resources as references

- Linking a project between GitHub and local:
    - [From GitHub to local](https://happygitwithr.com/new-github-first.html)
    - [From local to GitHub](https://happygitwithr.com/existing-github-last.html)


-----

-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: Reproducible Reports with R Markdown

```{r thurs-date}
cat(thurs_date_pretty)
```

From today's class, students are anticipated to be able to:

- Use basic markdown features
- Write documents in markdown on GitHub and RStudio, and render these documents to html and pdf with RStudio.
- Choose whether html or pdf is an appropriate output
- Style an Rmd document by editing the YAML header
- Demonstrate at least two Rmd code chunk options

#### Prepare for Class

Take about 30 minutes to get acquainted with the following before coming to class:

- Watch STAT 545 Episode 3-A: Reproducible Reports with R Markdown (**launched Tuesday at 11:00am PST**)
- Read the [Official R Markdown Tutorial](https://rmarkdown.rstudio.com/lesson-1.html) from the "Introduction" up to and including the "Inline Code" section.

#### During Class

- 9:30 - 9:50: Vincenzo demonstrates markdown, R Markdown, and rendering/knitting files.
- 9:50 - 10:00: Quiz
- 10:00 - 11:00: Students continue working on:
    - Collaborative Milestone 1, especially formatting their documents with markdown features.
    - Worksheet 1-A, as needed.
    
__TA's__: Victor and Icíar

__Quiz__: True or False:

1. Since GitHub only displays the code behind an html file, we need to output to pdf if we want to be able to view the rendering on GitHub. 
2. It doesn't make sense to output an .Rmd file to markdown, because .Rmd is already markdown. 

#### Useful Resources to refer to

Simple cheat sheets:

- [Simple markdown cheat sheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
- [YAML headers options](https://bookdown.org/yihui/rmarkdown/html-document.html)

Fully loaded cheat sheets:

- [R Markdown cheat sheet](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)
- [R Markdown reference guide](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf?_ga=2.177968037.1059384083.1597196687-1784159993.1567907747)

Note that many cheat sheets can be found from RStudio: go to `Help` > `Cheatsheets`

#### Interesting Reads

- [WYSIWYG is dead](https://medium.com/@ayman/wysiwyg-is-dead-d225276ed53)
    - An entertaining and concise argument against using "WYSIWYG" editors like Microsoft Word.

-----

-----

## Friday Office Hour

__September 18, 2020 from 16:00-17:00 PST__

Join Almas and Diana to discuss anything about the course: content, structure, deliverables, etc. 

_Note_: No office hour is being held on Wednesday.

-----

-----

<!-- ******PROJECT****** -->

## Collaborative Project Milestone 1

**Due:** ~~Friday, September 18~~ Saturday, September 19  at 23:59 PST

We recommend you start your projects Tuesday in class. You can view instructions for Milestone 1 [here](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/collaborative-project/milestone1/README.md#stat-545a-collaborative-project-milestone-1)

-----

-----

<!-- ******WORKSHEET****** -->

## Worksheet 1A

**Finish By:** Friday, September 18 at 23:59 PST **(Not for grades -- no need to submit!)**

Continue working on Worksheet 1A this week, as needed. 

-----

