---
title: "STAT 545 Checklist: Week 2-B"
subtitle: "Version 1.0"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
week_num <- 11  # 1 through 13; Week 7 ended 545A.
#-------------
source(here::here("content", "dates.R"))
library(stringr)
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
mon_date <- lec0 + days((week_num - 1) * 7 - 1)
sat_date <- mon_date + days(5)
cat(format(mon_date, "%A, %b %d"), "-", 
    format(sat_date, "%A, %b %d"))
```

A complete list of the things you'll need to do for STAT 545B this week.

This week's schedule. Assessments are in __bold__. 

See the [calendar](https://stat545.stat.ubc.ca/calendar) for a visual view of these things (except for lecture prep)

### Monday

- _No worksheet this week_
- Start lecture preparation (see notes)

### Tuesday

- [ ] Attend lecture 9:30am - 11:00am PST
- [ ] Prepare: Pre-readings by 09:30am PST
- [ ] Prepare: Watch pre-class video by 09:30am PST
- Start Assignment 3-B

### Wednesday

- [ ] __Complete Quiz 7-B by 11:00am PST (on canvas)__

### Thursday

- [ ] Pre-readings by 9:30am PST
- [ ] (Optional) Attend office hours at 16:00 - 17:00 PST in the regular "classroom".
- [ ] Attend lecture 9:30am - 11:00am PST

### Friday

- [ ] __Submit Quiz 8-B by 11:00am PST__
- [ ] Vote for your favourite topics to see in the last class of STAT 545B.
- [ ] Get your questions for the teaching team into Slack by mid-day (we can't necessarily be active on Slack on evenings and weekends)

### Saturday

- _No worksheet this week_
- [ ] __Submit your Assignment 3-B URL to canvas by 23:59 PST__