---
title: "STAT 545A: Week 3"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 3  # 1 through 14
#-------------
source(here::here("content", "dates.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec0 + ddays((week_num - 1) * 7)
tues_date_pretty <- paste0(
  month(tues_date, label = TRUE), " ", 
  day(tues_date), ", ", 
  year(tues_date)
)
thurs_class_num <- paste0(str_pad(week_num * 2 - 2 + 1, width = 2, pad = 0), letter)
thurs_date <- tues_date + ddays(2)
thurs_date_pretty <- paste0(
  month(thurs_date, label = TRUE), " ", 
  day(thurs_date), ", ", 
  year(thurs_date)
)
fri_date <- tues_date + ddays(3)
fri_date_pretty <- paste0(
  month(fri_date, label = TRUE), " ", 
  day(fri_date), ", ", 
  year(fri_date)
)
```


-----

<!-- ******WORKSHEET****** -->

## Worksheet `r paste0(week_num - 1, letter)`

**Due:** Friday, `r fri_date_pretty` at 23:59 PST

[.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_02a.ipynb); or [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_02a.ipynb)


-----

----- 

<!-- ******TUESDAY'S CLASS****** -->

## Tuesday's Class `r tues_class_num`: Data Wrangling I

```{r tues-date}
cat(tues_date_pretty)
```

From today's class, students are anticipated to be able to:

+ Recognize the advantages of the tidyverse compared to base R with respect to good coding practice
+ Subset and rearrange data with dplyr
+ Use piping when implementing function chains
+ Explore data in tibbles

#### Prepare for Class

Take about 30 minutes to get acquainted with the following before coming to class:

- Watch the [STAT 545 Video Series: Class `r tues_class_num`](https://youtu.be/Gms3zSPqCk8)
- Follow through [Jenny Bryan's Introduction to dplyr](https://stat545.com/dplyr-intro.html) at your own pace; this is optional, but very helpful in getting familiar with dplyr! You will have the chance to practice more in this week's worksheet.

#### During Class

+ 9:30 - 9:50: In class demo, covering:
  + tidyverse
  + dplyr
  + piping
  + tibbles 
  
+ 9:50 - 10:00: Quiz.

+ 10:00 - 10:05: Break.

+ 10:05 - 10:45: Lecture worksheet.

Complete the **Class 3-A Quiz** on Canvas by **Wednesday, September 23rd** at **11:00am PST.**

#### Resources

We have compiled a list of resources for data manipulation [here](https://stat545.stat.ubc.ca/resources/r-data-manipulation/). These resources are available for you to consult concepts, get more advanced knowledge, or explore other topics at your own pace (if you wish to do so). The [dplyr cheatsheet](http://gauss.inf.um.es/tabular/www/data-transformation.pdf) should come in handy for this class.

-----

-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: ggplot2 I

```{r thurs-date}
cat(thurs_date_pretty)
```

From today's class, students are anticipated to be able to:

+ Identify the seven components of the grammar of graphics underlying ggplot2
+ Recognize the advantages of ggplot2 over plotting with base R and lattice
+ Use different geometric objects and aesthetics to explore various plot types

#### Prepare for Class

Allocate about 30 minutes to get familiar with the contents for this class - guaranteed to make your life easier!

- Watch the STAT 545 Video Series: Class `r thurs_class_num`
- With R Studio handy, follow through sections 3.1 to 3.4 of [R4DS Data Visualization](https://r4ds.had.co.nz/data-visualisation.html#introduction-1) at your own pace. Don't worry if you don't cover it all, we will go through these concepts in class!

#### During Class

+ 9:30 - 9:50: In-class demo, covering:
  + Why data visualization? Just plot it + The grammar of graphics (~10 minutes)
  + In-class demo of creating a scatterplot (~10 minutes)
  
+ 9:50 - 10:00: Quiz.

+ 10:00 - 10:20: Introduce the Mini Data Analysis Project.

+ 10:20 - 10:45: Lecture Worksheet + Share your work through Slack!

Complete the **Class 4-A Quiz** on Canvas by **Friday, September 25th** at **11:00am PST.** 

#### Resources

A comprehensive list of [data visualization resources](https://stat545.stat.ubc.ca/resources/r-vis/) has been compiled to save you time browsing through the endless resources that are available out there. There are cheatsheets and quick resources (most notably the [ggplot 2 cheatsheet](https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)), books, and other fun things!

-----

-----

<!-- ******OFFICE HOURS****** -->

## Friday Office Hour

**September 25th, from 16:00-17:00 PST.**

Join the TAs to discuss anything about the course: content, structure, deliverables, etc. Can't make it? No worries - reach us through Slack / Canvas / email with your questions.

-----

-----

<!-- ******PROJECT****** -->

## Collaborative Project Milestone 2

**Due:** Friday, `r fri_date_pretty` at 23:59 PST

-----
