---
title: "STAT 545A: Week 4"
output: 
  html_document:
    toc: true
    toc_float: true
---


```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 4  # 1 through 14
#-------------
source(here::here("content", "dates.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec0 + ddays((week_num - 1) * 7)
tues_date_pretty <- paste0(
  month(tues_date, label = TRUE), " ", 
  day(tues_date), ", ", 
  year(tues_date)
)
thurs_class_num <- paste0(str_pad(week_num * 2 - 2 + 1, width = 2, pad = 0), letter)
thurs_date <- tues_date + ddays(2)
thurs_date_pretty <- paste0(
  month(thurs_date, label = TRUE), " ", 
  day(thurs_date), ", ", 
  year(thurs_date)
)
fri_date <- tues_date + ddays(3)
fri_date_pretty <- paste0(
  month(fri_date, label = TRUE), " ", 
  day(fri_date), ", ", 
  year(fri_date)
)
```


-----

<!-- ******WORKSHEET****** -->

## Worksheet 3A

**Finish By:** Saturday, October 3 at 23:59 PST 

[.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_03a.ipynb) or [view it on GitHub](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_03a.ipynb)

-----

----- 

<!-- ******TUESDAY'S CLASS****** -->

## Tuesday's Class `r tues_class_num`: Data Wrangling II

```{r tues-date}
cat(tues_date_pretty)
```

From today's class, students are anticipated to be able to:

+ Grouping data to compute summarized functions using `dplyr::group_by()` and `dplyr::summarize()`
+ Compute new columns using `mutate()`
+ Use `dplyr::across()` to use functions with specific columns

#### Prepare for Class

- Watch the [STAT 545 Video Series: Episode 6-A](https://youtu.be/38BA_v7BwKk)
- We recommend you read / skim through the following resources for more details: 
   - [Jenny's "dplyr single table verbs"](https://stat545.com/dplyr-single.html) for dplyr verbs.
   - [Hadley's "across" blog post](https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-colwise/) to learn more about `across()`

Some useful (but not mandatory) readings are:

- [Jenny's dplyr tutorial](https://stat545.com/dplyr-single.html)
- [dplyr vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html)

#### During Class

+ 9:30 - 9:50: In class demo, covering:
  + group_by
  + summarize
  + across
+ 9:50 - 10:00: Quiz.
+ 10:00 - 10:05: Break.
+ 10:05 - 10:45: Lecture worksheet.

**Complete the Class 6-A Quiz on Canvas by Wednesday, September 30th at 11:00am PST.**

-----

-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: ggplot2 II 

```{r thurs-date}
cat(thurs_date_pretty)
```

From today's class, students are anticipated to be able to:

+ Become familiar with customizing `ggplot2` graphs 
+ Understand what makes data visualizations *effective*

#### Prepare for Class

- Watch the [STAT 545 Video Series: Episode ](link)

Some useful (but not mandatory) readings are:

- [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/introduction.html) by Claus Wilke.
- [Visualization Analysis and Design](https://www-taylorfrancis-com.ezproxy.library.ubc.ca/books/9780429088902) by Tamara Munzner.
- [STAT545.com](https://stat545.com/effective-graphs.html) - Effective Graphics by Jenny Bryan.
- [ggplot2 book ](https://ggplot2-book.org/)by Hadley Wickam.
- [Callingbull.org](https://callingbull.org/tools.html) by Carl T. Bergstrom and Jevin West.

#### During Class

+ 9:30 - 9:50: In class demo, covering:
  + customizing ggplot2 graphs
  + effective visualizations
+ 9:50 - 10:00: Quiz.
+ 10:00 - 10:05: Break.
+ 10:05 - 10:45: Lecture worksheet.

**Complete the Class 7-A Quiz on Canvas by Friday, October 2nd at 11:00am PST.**

## Friday Office Hour

October 2nd, from 16:00-17:00 PST.

Join the TAs to discuss anything about the course: content, structure, deliverables, etc. Can’t make it? No worries - reach us through Slack / Canvas / email with your questions.

## Deadline: Mini Data Analysis I

**Due:** Saturday, October 3rd 23:59 PST.

-----
