---
title: "STAT 545A: Week 1"
output: html_document
---

**UNDER DEVELOPMENT**


```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 1  # 1 through 14
#-------------
source(here::here("content", "lec1.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec1 + ddays((week_num - 1) * 7)
tues_date_pretty <- paste0(
  month(tues_date, label = TRUE), " ", 
  day(tues_date), ", ", 
  year(tues_date)
)
thurs_class_num <- paste0(str_pad(week_num * 2 - 2 + 1, width = 2, pad = 0), letter)
thurs_date <- tues_date + ddays(2)
thurs_date_pretty <- paste0(
  month(thurs_date, label = TRUE), " ", 
  day(thurs_date), ", ", 
  year(thurs_date)
)
fri_date <- tues_date + ddays(3)
fri_date_pretty <- paste0(
  month(fri_date, label = TRUE), " ", 
  day(fri_date), ", ", 
  year(fri_date)
)
```


-----

<!-- ******WORKSHEET****** -->

## Worksheet 1A

**Finish By:** Friday, September 18 at 23:59 PST **(Not for grades -- no need to submit!)**

For the first two weeks, we'll be working on this worksheet in class. This worksheet is intended to:

- Get you used to filling out the worksheets; and
- Get you up-to-speed with using R.

-----

----- 

<!-- ******TUESDAY'S CLASS****** -->

## Tuesday's Class `r tues_class_num`: Class Cancelled

```{r tues-date}
cat(tues_date_pretty)
```

**Imagine Day: class cancelled**

Prepare for the course:

+ Watch the Intro to STAT 545 Video Series video.
+ Install the software needed for STAT 545A by following along the tutorial ["Software Installation for STAT 545"](/software-stack).

-----

-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: Intro to R and STAT 545

```{r thurs-date}
cat(thurs_date_pretty)
```

<!-- From today's class, students are anticipated to be able to: -->

<!-- - FILL_THIS_IN -->

#### Prepare for Class

Have you completed the exercises in "Class 00A"? Do that first before starting!

- Watch the STAT 545 Video Series: Class `r thurs_class_num`
- Read...

#### During Class

+ Intro to STAT545A & what to expect from the class - enter syllabus (~20 min)
+ 5 minute break + additional time in case there are troubleshooting issues with R & RStudio that need to be solved individually.
+ Why R? + Lecture worksheet / In-class demo (~50 minutes)
  + Rather than using breakout rooms in the first class (since it may be the first time using R and RStudio for many), I think alternating between an in-class demo where everything in [2.5 Orientation to R](https://stat545guidebook.netlify.app/introduction-to-r.html) & "don't save your workspace" is demonstrated while alternating with students completing the worksheet may be good. 
  + Example of the workflow (1) Vincenzo demonstrates Functions I and Functions II, could simply be an improvised demo in R (2) Students complete the relevant section of the worksheet, and click "yes" on Zoom when they are done (3) When all or almost all students have clicked "yes" (if there is a couple that have not, TAs reach out directly to ask), go on to the next task.

-----




