---
title: "STAT 545A: Week 7A"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
week_num <- 7  # 1 through 14
#-------------
source(here::here("content", "dates.R"))
library(stringr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "asis")
letter <- if (week_num <= 7) "A" else "B"
tues_class_num <- paste0(str_pad(week_num * 2 - 2, width = 2, pad = 0), letter)
tues_date <- lec0 + ddays((week_num - 1) * 7)
tues_date_pretty <- paste0(
  month(tues_date, label = TRUE), " ", 
  day(tues_date), ", ", 
  year(tues_date)
)
wed_date <- tues_date + ddays(1)
wed_date_pretty <- paste0(
  month(wed_date, label = TRUE), " ", 
  day(wed_date), ", ", 
  year(wed_date)
)
thurs_class_num <- paste0(str_pad(week_num * 2 - 2 + 1, width = 2, pad = 0), letter)
thurs_date <- tues_date + ddays(2)
thurs_date_pretty <- paste0(
  month(thurs_date, label = TRUE), " ", 
  day(thurs_date), ", ", 
  year(thurs_date)
)
fri_date <- tues_date + ddays(3)
fri_date_pretty <- paste0(
  month(fri_date, label = TRUE), " ", 
  day(fri_date), ", ", 
  year(fri_date))
  sat_date <- tues_date + ddays(4)
sat_date_pretty <- paste0(
  month(sat_date, label = TRUE), " ", 
  day(sat_date), ", ", 
  year(sat_date)
)

```

-----

<!-- ******WORKSHEET****** -->

## Worksheet `r paste0(week_num - 1, letter)`

**Due:** Saturday, October 24 at 23:59 PST (submit your file to canvas)

-----

----- 

<!-- ******TUESDAY'S CLASS****** -->

## Tuesday's Class `r tues_class_num`: Reading and Writing Data

```{r tues-date}
cat(tues_date_pretty)
```

From today's class, students are anticipated to be able to:

- Read and write a delimited file, like a csv, from R using the `readr` package.
- Make relative paths using the `here::here()` function.
- Read data from a spreadsheet
- Read and write R binary files (rds files) from R.

#### Prepare for Class

Read/watch one of the following two resources before class:

- Watch the [STAT 545 Video Series: Class `r tues_class_num`](https://youtu.be/2nHuNu6Zaqk)
- Read the ["Writing and Reading files"](https://stat545.com/import-export.html) chapter of stat545.com.


#### During Class

- **Quiz**: Complete the Class `r tues_class_num` Quiz on Canvas by Wednesday, `r wed_date_pretty` at 11:00am PST.

-----

-----

<!-- ******THURSDAY'S CLASS****** -->

## Thursday's Class `r thurs_class_num`: More R, and a tour of other things

```{r thurs-date}
cat(thurs_date_pretty)
```

By the end of this class, we will cover as much of the following as we can:

- More R Basics:
  - vectors and lists
  - Make a reproducible example using the `reprex` package.
  - Use of {}.
  - attributes
  - style guides
- Turning your GitHub repository into a Website
- Turning your Rmd into a presentation (2 min)

These three topics were the top three chosen in the poll.

| Lecture | Demonstration | View |
|---------|-----------|------|
| 13-A: Choose your adventure | [.Rmd](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/demonstrations/demo13a-misc.Rmd) | [Knitted demo](/demonstrations/demo13a-misc) |

#### Prepare for Class

Before class:

- Watch the STAT 545 Video Series: Class `r thurs_class_num` (to be posted)

Some useful (but not mandatory) resources are:

- The book [Advanced R](https://adv-r.hadley.nz/) is an approachable, free, online book for learning more about R.
  - [Vectors chapter](https://adv-r.hadley.nz/vectors-chap.html) for vectors and lists. 
  - [Subsetting chapter](https://adv-r.hadley.nz/subsetting.html) for subsetting vectors.
  - [Functions chapter](https://adv-r.hadley.nz/functions.html)
  - [Environments chapter](https://adv-r.hadley.nz/environments.html)
  - [S3 chapter](https://adv-r.hadley.nz/s3.html)

#### During Class

- In-class demo of more R things, and a tour of other topics.
- **No quiz**

-----

-----

## Friday Office Hours from 16:00 - 17:00 PST:

Join Victor for office hours regarding this week's content, the milestones or other questions about R. Can't come to office hours? Reach out on Slack/Canvas/Email. 

-----

-----

<!-- ******PROJECT****** -->

## Mini Analysis Milestone 3 

**Due:** Saturday, `r sat_date_pretty` at 23:59 PST

| Milestone | Instructions | .Rmd | Checklist |
|-----------|--------------|------|-----------|
| Milestone 3 | [view](https://stat545.stat.ubc.ca/mini-project/mini-project-3/) | [.Rmd](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/mini-project/mini-project-3.Rmd) | [view](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/mini-project/mini-project-3-checklist.md) |

-----
