---
title: "Who to contact"
output: html_document
---

Whether you're sending an email, or tagging a member of the teaching team, please use this as a guideline for determining who to contact. You can find the contact info of the teaching team under the [teaching team](#teaching_team) section.

## Have an issue with the way you were evaluated?

Your TA will have left an Issue on your homework repo. Continue the conversation there.

__But I really don't want anyone else but the teaching team to see my comment!__

We still encourage you to muster the courage to continue the discussion in the Issue. Otherwise, send an email directly to the TA that graded your work.

## Have an issue with the way you were evaluated, even after discussion with the TA?

Your TA will have left an Issue on your homework repo. Continue the conversation there, _this time tagging the instructor_.

__But I really don't want anyone else but the teaching team to see my comment!__

We still encourage you to muster the courage to continue the discussion in the Issue. Otherwise, send an email directly to the instructor.