---
title: "assignment_04"
author: "YOUR_NAME"
date: "Updated `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 04

In this assignment, there are three tasks:

1) Run Dash app from the command line
2) Practicing with Dash components
3) Teamwork document

You will start with some starter code for a Dash app and then you will then add the components below.
I encourage you to add them one at a time rather than all at once!

### Task 1: Run the app (40%)

- Open a Terminal window (RStudio or system)
- Navigate to the appropriate folder using: `cd path/to/your/file/app.R`
- Type `Rscript app.R`
- You will see a message similar to: 

```
Fire started at 127.0.0.1:8050
start: 127.0.0.1:8050
```
- Copy the address (numbers after start) and paste them into a browser window.
- Make sure the app works as you expect and displays the "Hello World!" header.

#### Grading for Task 1

- 30 points: TA was able to run the app without errors.
- 15 points: TA was able to run the app with a few minor fixes to the code.
- 0 points: TA was not able to run the app, or major fixes were required.

### Task 2: Add components (50%)

In this section, you will create 5 componens to your DashR app using the `diamonds` dataset.
To be clear, it does not really matter the details (as long as it's appropriate) of what you put in here because we are just assessing the mechanics of including these components in a Dash app.

#### Grading for Task 2

Each component is worth a certain number of points (total of 50).
If your component is present, functional, and the code is correct, you will get full marks.

- Task 2.1 - 5 points
- Task 2.2 - 5 points
- Task 2.3 - 10 points
- Task 2.4 - 10 points
- Task 2.5 - 20 points

#### Task 2.1 - Add a heading and a subheading component

- Add an HTML H1-level header.
- Add an HTML H3-level header.

#### Task 2.2 - Add a Markdown component (you can fill it with random text [from here](https://www.lipsum.com))

- Add a markdown component that includes the following things:
  - Add a link.
  - Add some **bolded** text.
  - Add some _italic_ text.
  - Add a static image referencing an image in your repo or a URL (make sure you have permission to use the image).

#### Task 2.3 - Add a dropdown component

- Add a dropdown component that corresponds to the `clarity` column of the `diamonds` dataframe.
- There should be no repeats in the dropdown options.
- It is not required to link your dropdown to the graph component in Task 2.5 (you will do this in assignment 5 next week).

#### Task 2.4 - Add a slider component with labels at each point 

- Add a slider component that corresponds to the `cut` column of the `diamonds` dataframe.
- The labels on the slider should correspond to the quality of the cut (Fair, Good, Very Good, Premium, Ideal).
- There should be no repeats in the slider options.
- It is not required to link your slider to the graph component in Task 2.5 (you will do this in assignment 5 next week).

#### Task 2.5 - Add two graph components using ggplot and ggplotly

- Using `ggplot`, create a histogram of the diamond price on the x-axis and number of diamonds on the y-axis.
- Using `ggplot`, create a second plot (of your choice)
- Create a `ggplotly` object by passing the `ggplot` object into the `ggplotly` function (from the `plotly` library).
- Add two graph components using the ggplotly objects you created.

### General

After you have included all the components, run the app again and make sure it runs!
If it does not, you will lose marks not just in this task, but also in Task 1!

### Task 3: Complete project reflection document (10%)

Complete the [teamwork reflection document](https://stat545.stat.ubc.ca/evaluation/teamwork/) for your project project so far.
You will find the RMd file that you need to fill out in your assignment repo.
DO NOT FORGET to also rate yourself for each question.

#### Grading for Task 3

- This teamwork reflection document is for completion marks only.
- At the end of the course, both teamwork reflection files will be looked at and a final teamwork score will be awarded (worth 10% of the course)
