---
title: "Assignments"
date: "Updated `r Sys.Date()`"
---

Your hub for information related to assignments. 

## Schedule

Here are the deadlines for assignments, with links (to appear after assignments are released).

A GitHub Issue will be posted in the [Course repo](https://github.com/STAT547-UBC-2019-20/Discussions) repo whenever a new assignment is released. The @students tag will be used so you should get an email notification with it as well.

All submissions are due by Saturday at 18:00 with the regular [grace period](https://stat545.stat.ubc.ca/policies/).

### STAT 547M

| Assignment  | Due Date | Accept assignment  | Solutions|
|-------------|----------| ---------------------------|----------|
| [Participation](participation/) | Saturday Apr 11 at 18:00 | [Accept assignment](https://classroom.github.com/a/uYT4-Doe) | |
| [Assignment 1](/evaluation/assignment_01/assignment_01) | Saturday Mar 7 at 18:00 | [Accept assignment](https://classroom.github.com/a/b3vITuTN)| [solution](/evaluation/assignment_01/solutions_assignment_01)|
| [Assignment 2](/evaluation/assignment_02/assignment_02) | Saturday Mar 7 at 18:00 | [Accept assignment](https://classroom.github.com/a/hTfSIzg6)|[solution](/evaluation/assignment_02/solutions_Assignment_02)|
| [Assignment 3](/evaluation/assignment_03/assignment_03) | Saturday Mar 14 at 18:00 | [Accept assignment](https://classroom.github.com/a/5OgwN-FJ)| |
| [Assignment 4](/evaluation/assignment_04/assignment_04) | Saturday at 18:00 | [Accept assignment](https://classroom.github.com/a/dEw9SDMF)| [solution](https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/assignment_04/assignment_04solutions.R) |
| [Assignment 5](/evaluation/assignment_05/assignment_05) | Saturday at 18:00 | [Accept assignment](https://classroom.github.com/a/dislHsTK) | [app.R](https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/assignment_05/app.R); [components](https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/assignment_05/A05_components.R); [functions](https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/assignment_05/A05_functions.R)|
| [Assignment 6](/evaluation/assignment_06/assignment_06) | Sunday at 18:00 (extended because it was a late release) | [Accept assignment](https://classroom.github.com/a/W5eJpOnI)| |

### STAT 545A

| Assignment  | Assignment Due Date |
|-------------|---------------------|
| [Assignment 01](/evaluation/hw01/hw01) | September 17, 2019  |
| [Assignment 02](/evaluation/hw02/hw02) | September 24, 2019  |
| [Assignment 03](/evaluation/hw03/hw03) | October 01, 2019    |
| [Assignment 04](/evaluation/hw04/hw04) | October 08, 2019    |
| [Assignment 05](/evaluation/hw05/hw05) | October 17, 2019    |

## Grading

The assignments make use of [UBC MDS's rubrics](https://github.com/UBC-MDS/public/tree/master/rubric). Within each assignment, we let you know which rubrics are being used and where, along with their weighting. Each rubric typically has six "levels" defined by letter grades, which map to the following percentages as [defined by UBC](http://www.calendar.ubc.ca/Vancouver/index.cfm?tree=3,42,96,0):

| Category | Grade Range |
|----------|-------------|
| No attempt (0)          | 0 |
| Poor (F)                | 0 - 49% |
| Unsatisfactory (D)      | 50% - 54% |
| Satisfactory (C- to C+) | 55% - 67% |
| Good (B- to B+)         | 68% - 79% |
| Excellent (A- to A+)    | 80% - 100% |

## Managing repositories

You will have to manage several repositories in STAT 547:

- One repository **per assignment**
- One repository for all your class participation files
- One repository for each of the two teamwork assignments
- One repository for your team project

It's important that you keep things organized locally!
I suggest a STAT547 folder and each repository cloned as a subfolder.

## Working on your Assignment

As you work on your assignment, you should commit and push your progress to GitHub. As a word of advice:

**Commit your work often!**

**Commit your work often!**

**Commit your work often!**

Too many times, I see students wait until they finish their assignments to commit and push to GitHub. This is a very bad idea for at least two reasons:

1. If you submit your work late, we are forced to give you the late penalty. But if you've been committing your work, we can at least look at your repo as it was after the latest commit before the deadline.
2. Your workflow will not be as effective as it could be by using version control.

## Tidy Submission

Each assignment will have some marks set aside for a "tidy" submission, which is defined here. If there's any further uncertainty in determining a grade for the tidy submission portion, the [UBC MDS mechanics rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_mech.md) will be referred to.

Before submitting your work, make sure it's tidy:

- Your work must be reproducible from beginning to end. That is, a member of the teaching team should be able to run all code error-free and reproduce the output files. 
- Your scripts do not contain code that installs packages (this is not good practice anyway) – note that this is different from loading packages with the `library()` function, which is good!
- All R Markdown files are `knit`ted to ~~an output readable on GitHub (probably `github_document` or `pdf_document`).~~ a readable output. This means linking to HTML files if you make them (see section on "Viewing and linking to HTML files"). You can also knit to `output: github_document` if you want a markdown file that renders nicely for GitHub.

Here is how you submit your homework:

1. If you're working locally (i.e., on your hard drive), push your work to your GitHub assignment repository.
2. On your GitHub homework repository, [tag a release](https://help.github.com/articles/creating-releases/).
	- As a "tag version", we recommend putting 'v1.0' for each assignment
	- If you want to make changes to your release before the deadline, just tag a new release like `v1.1`.
3. Go to the course page on [UBC canvas](https://canvas.ubc.ca), and find the corresponding assignment submission. Submit a URL to the latest release of your assignment. 
	- You can find this by clicking on the "release" button on your GitHub homework repository, on (for example) the `v1.0` text. 

## Viewing and linking to HTML files

Viewing an HTML file on GitHub only shows you the HTML code, not the rendered script. You'll need to provide a link to a rendered, viewable version of each HTML file you produce. Here's how you do that using [_GitHub Pages_](https://pages.github.com/):

1. Enable "GitHub pages" on your repo:
    - Go to "settings" on your repo, and stay on the default "Options" tab.
    - Scroll down to the "GitHub Pages" section.
    - Under "Source", click the "None" drop-down button, and select the branch you want to turn into a website (probably "Master").
2. Also under the "GitHub Pages" section, you'll find your website URL. Make note of this URL.
	- This URL will show a rendered version of your repo's README, but this is not important.

Just by enabling GitHub Pages, your HTML files are now viewable rendered by your browser. Technically, you just turned your GitHub repo into a website. The only trick is _navigating_ to that HTML page, since there's no default _interface_ to your website.

3. Obtain the URL to  HTML file on your repo:
    - Start with your GitHub Pages URL that you made note of in Step 2. This points to the root of your repository. 
    - Get the path to an HTML file you want to view. It should be something like `/path/to/file.html` (in this case, `file.html` lives in the `to` folder, which lives in the `path` folder in the root of your repo). 
    - Append the path to the HTML file to your GitHub Pages URL. Try the URL to see that it works.
4. Make it easy for a visitor to your repo to find the rendered HTML file! Add a link to the rendered HTML file somewhere in your repo, probably in a README file in your homework folder.
