---
title: "Participation Assessment"
date: "Updated `r Sys.Date()`"
---

__Due__: Saturday, April 10, at 18:00.

The intent of the participation assessment is to encourage following along with class activities, which are usually coding sessions. 
You'll be putting all your in-class work in your own participation repository hosted on your GitHub user account, which we will evaluate at the end of the course.

## Expectations

In short, we're evaluating _completeness_, not _correctness_. Specifically:

Your participation component will be evaluated by the completeness of your repository. You'll be prompted in class when you should be contributing to your participation repository. 

### Completeness (70%)

Your repository should be _complete_ with all in-class exercises. Your work should resemble an honest _attempt_ at the activities, but __does not__ need to be anywhere near "correct" -- even completely failing at an activity will earn you full marks here!

Of 12 classes, we will mark your 10 best so each class is worth 1% of your STAT 547 course grade.

### Documentation (30%)

Your repository should be _well-documented_. 

- 10%: Does your main README orient a stranger to your repository?
- 10%: Will a stranger be able to figure out what the main files of your repository are for, and where they are located?
- 10%: Are the contents of your files human readable? Although we aren't expecting publication-quality prose, there should be a moderate level of readability of your scripts to earn you full points here.

## STAT 547 Participation checklist


## STAT 545 Participation Check List
 
Below is a checklist with all the materials needed to get full participation marks. Instructor version of the scripts run in class are provided for your reference.
 
Note that instructor copy is just for your reference. You cannot just copy-paste the code written by the instructors and submit it as your participation. It is the responsibility of every student to be aware and adhere to the policies on plaigiarism: [Code Plagiarism](https://stat545.stat.ubc.ca/policies/). 

1. **Class Meeting 1 Introduction to STAT 545 and GitHub**   
    - Register a GitHub account
    - Share your username by filling out this [survey](https://ubc.ca1.qualtrics.com/jfe/form/SV_8jKz3FaT7w5EHfT)
    - Create and populate ```navigating_github.md``` with several links
2. **Class Meeting 2 Introduction to R**   
    - Provide the R script ```cm002_R_exploration.R``` file. Instructor version can be found [here](https://github.com/vincenzocoia/STAT545-participation/blob/master/tools/cm002-r_exploration.R)
3. **Class Meeting 3 Authoring**  
   - Populate ```navigating_github.md``` document with some markdown features
   - Convert the ```.md``` file into both ```pdf``` and ```html``` and add them to your repo
   - Upload ```rmd_exploration.Rmd``` and its output formats (```md```, ```pdf``` and ```html```)
   - Upload ```rmd_exploration-slides.Rmd``` both as ```Rmd``` and ```html```(or ```pdf```) formats
4. **Class Meeting 4 The version control workflow**   
   - nothing is required for submisison 
5. **Class Meeting 5 Intro to plotting with ggplot2, Part I**  
   - Complete [cm005-ggplot_intro.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm005-exercise.Rmd) worksheet. Instructor version can be found [here](https://github.com/vincenzocoia/STAT545-participation/blob/master/plotting/cm005-ggplot_intro.Rmd)
   - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
6. **Class Meeting 6 Intro to data wrangling, Part I** 
   - Complete [cm006-dplyr_exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm006-exercise.Rmd) worksheet. Instructor version can be found [here](https://github.com/wvictor14/STAT545-participation/blob/master/cm006-exercise.Rmd)
   - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
7. **Class Meeting 7 Intro to data wrangling, Part II**
   - Complete [cm007-exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm007-exercise.Rmd) worksheet. Instructor version can be found [here](https://github.com/vincenzocoia/STAT545-participation/blob/master/wrangling/cm007-exercise.rmd)
   - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
8. **Class Meeting 8 Intro to plotting with ggplot2, Part II**  
   - Complete [cm008-exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm008-exercise.Rmd) worksheet. Instructor version can be found [here](https://github.com/vincenzocoia/STAT545-participation/blob/master/plotting/cm008-exercise.Rmd)
   - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
9. **Class Meeting 9 Tidy Data and Pivoting** 
   - Complete [cm009-exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm009-exercise.Rmd) worksheet. Instructor version can be found [here](https://github.com/vincenzocoia/STAT545-participation/blob/master/wrangling/cm009-exercise.Rmd)
   - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
10. **Class Meeting 10 Tibble Joins** 
    - Complete [cm010-exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm010-exercise.Rmd) worksheet. Instructor version can be found [here](https://github.com/vincenzocoia/STAT545-participation/blob/master/wrangling/cm010-exercise.Rmd)
    - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
11. **Class Meeting 11 File input/output (I/O)**
	- Complete the steps described in [lesson 11](https://stat545guidebook.netlify.com/file-inputoutput-io.html).
	- Submit ```.R``` script with your work
12. **Class Meeting 12 Working with factors in R**
    - Complete [cm012-exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm012-exercise.Rmd) worksheet. Instructor version can be found in the guide [lesson 12](https://stat545guidebook.netlify.com/working-with-factors-in-r.html)
    - Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
13. **Class Meeting 13 Effective Visualizations**
	- Complete [cm013-exercise.Rmd](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/cm013.Rmd) worksheet. Instructor version can be found in the guide [lesson 13](	https://stat545guidebook.netlify.com/effective-visualizations.html#plotly-demo-10-mins)
	- Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)
14. **Class Meeting 14 The Model-Fitting Paradigm in R**
	- Complete [cm014-exercise.Rmd](https://github.com/STAT545-UBC/Classroom/blob/master/tutorials/cm014-exercise.Rmd) worksheet. This worksheet is closely alligned with [this tutorial](https://cfss.uchicago.edu/notes/linear-models/)
	- Submit ```.Rmd``` file along with knitted version of your choice (```pdf```, ```md``` or ```html``` format)

## Submitting your participation repository

If you've completed Step 3 in the above "Setup" section, you don't have to do anything. We will grade your repository as it was on the last commit before the deadline.

