---
title: "Peer Reviews"
date: "Updated `r Sys.Date()`"
---


As part of this course you will be reviewing, commenting on, and marking other students' assignments. This is a mandatory part of the course and you will be marked on your peer reviews (15% of overall course mark).

Here is a template for giving a peer review: [markdown version](https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/peer-review-template.md) or [formatted version](/evaluation/peer-review-template).

## Schedule

Peer Reviews will be posted here as they are made available.

Here are the deadlines for peer reviews, with links (to appear after assignments are released). All submissions are due by 23:59.

### STAT 545A

| Peer Review    | Peer Review Due Date  |
|----------------|-----------------------|
|<a href="https://github.com/STAT545-UBC/STAT545-home/blob/master/content/evaluation/hw01/HTML-peer-review.html"> Peer Review 01 </a> | September 24, 2019 |
| Peer Review 02 | TBA|
| Peer Review 03 | TBA |
| Peer Review 04 | TBA |
| Peer Review 05 |TBA |

### STAT 547M

| Peer Review    | Peer Review Due Date  |
|----------------|-----------------------|
| Peer Review 06 | |    
| Peer Review 07 | |    
| Peer Review 08 | |    
| Peer Review 09 | |    
| Peer Review 10 | |    


## Peer Review Life Cycle

Here is the general flow that will happen for the peer reviews.

1. When a peer review is released, a GitHub Issue will be posted in the [Announcements](https://github.com/STAT545-UBC-hw-2019-20/Announcements) repo, tagging the teaching team and students.
2. Click the link in the table above to find a table outlining which two classmates you are to provide a review for, and where to find their homework submissions.
3. Navigate to your classmates' homework submissions, look it over, and open a new Issue on their homework repository with your review.
	- You might want to tag the reviewee, too, but not the teaching team. 
4. Upon completion, it would be useful for you to submit a link to the two reviews you left; do so on the UBC Canvas page for the peer review. We will be putting your grades there.

__If you do not find your github username on the list__: 

This probably means that we don't have you on the class roster.

1. Complete the peer review steps, but for two randomly chosen classmates.
2. Indicate that your name was not on the list when you make a submission through canvas.
3. Email the instructor with the situation, so that the class list can be updated. 

## Expectations

We will be using the [UBC MDS rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_peer-review.md) for assigning a letter grade to each review. 

## Resources

How to give a good peer review:

- Give thoughtful, constructive and considerate comments.
- Be specific and concise.
- Use the assignment rubric (above) for ideas about criteria to evaluate and comment on -- we've given you a template to work with [here](https://github.com/STAT545-UBC/Classroom/blob/master/assignments/peer-review-template.md).
- Try to learn something new and, if you succeed, point that out.
- If you can't find anything to praise or that you found helpful, then at least offer some suggestions in a kind way.

Peer reviewing and critiquing others' work is a useful skill to develop during your graduate studies. Although these links deal mainly with the peer review of academic papers, most of the key points are applicable to our peer review process.

- [Reviewing academic papers by Jeff Leek](https://github.com/jtleek/reviews/blob/master/README.md)
- [Edicts for peer reviewing (Ebb & Flow blog)](http://evol-eco.blogspot.ca/2014/09/edicts-for-peer-reviewing.html)
- [Faculty of 1000 Research: tips for peer reviewing](http://f1000research.com/peer-reviewing-tips)
- [The section entitled "How to perform the actual code review"](http://zonca.github.io/2014/08/code-review-for-scientific-computing.html)
