---
title: "Teamwork Document"
date: "Updated `r Sys.Date()`"
---

__Due__: April 4 2020.

# Team project reflection (10%)

The purpose of this individual report is to give you an avenue to present your viewpoint as to how the capstone project went, how the group worked together, and your role in the group. Each group member must complete this form to report on the contributions of **yourself** and ypur group partner. That information can, if needed, be used to adjust final grades of individuals. This is a private report, meaning that none of your classmates will see this report.

Evaluate	yourself and your group partner by	writing	the	number	that	best	reflects	the	extent	to	which	he/she
participated,	prepared,	helped	the	group	excel,	and	was	a	team	player.	Use	the	following	ratings:

| Rating | Description                                 |
|--------|---------------------------------------------|
| 4	     | Usually	(over	90%	of	the	time)            |
| 3	     | Frequently	(more	often	than	not)           |
| 2	     | Sometimes	(less	than	half	the	time)      |
| 1	     | Rarely	(never	or	once	in	a	great	while) |


**Preparation.**	Prepared	for	 group	meetings;	has spent time becoming familiar with the material relevant for the project; understands the project's goal and expectations;	does what they say they will do on time;	attends	and	is	on	time	to	group	meetings.

| Group member name | Preparation rating |
|-------------------|--------|
|                   |        |
|                   |        |


**Participation	&	communication.**	Articulates	ideas	effectively	when speaking	or	writing;	work	is without	grammatical	errors;	listens	to	others;	encourages	others	to	talk.

| Group member name | Participation	&	communication rating |
|-------------------|--------|
|                   |        |
|                   |        |


**Helps	group	excel.**	Expresses	great	interest	in	group	success	by	evaluating
ideas	and	suggestions;	initiates	problem	solving;	influences	and	encourages
others	to	set	up	high	standards;	doesn't	accept	just	any	idea	but	looks	for
the	best	ideas;	stays	motivated	from	beginning	to	end	of	project.

| Group member name | Helps	group	excel rating |
|-------------------|--------|
|                   |        |
|                   |        |


**Team	player	(cooperation).**	Knows	when	to	be	a	leader
and	a	follower;	keeps	an	open	mind;	compromises	when
appropriate;	can	take	criticism;	respects	others.

| Group member name | Team	player (cooperation) rating |
|-------------------|--------|
|                   |        |
|                   |        |


Below,	briefly	describe	the	specific	contribution(s)	each	team	member (**including yourself**)	made	to	your	project.	Point form	is	fine.	Specifically, comment on the following areas:

- how the team worked together as a whole, including:
    - what was your role in the group? That is, what sort of things did you do to contribute to the evolution of the project?
    - what were the roles of others in your group?
- what went well and poorly throughout the team project experience?

**(Optional) Feedback for teammates.** Is there anything you would like us to share with your teammates?

