---
title: "Special objects in R: Dates, Times, and Factors"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
knitr::opts_chunk$set(fig.width = 5, fig.height = 3, 
                      fig.align = "center", error = TRUE)
```

From today's class, students are anticipated to be able to:

- Reorder levels within factors according to various principles.
- Make a date and datetime object and extract components from these objects, using the lubridate package.

## Resources

Video lecture:

- [Special Data Types in R: Dates, Times, and Factors](https://youtu.be/TTNfLtEUFDQ)

Other resources, in addition to the notes below:

- For factors:
    - The [stat545.com](https://stat545.com/factors-boss.html) chapter on Factors
    - The [forcats](https://forcats.tidyverse.org) package page and reference guide on page. 
- For dates and times:
    - The [R4DS](https://r4ds.had.co.nz/dates-and-times.html) chapter on Dates and Times
    - The `tsibble` [vignette](https://cran.rstudio.com/web/packages/tsibble/vignettes/intro-tsibble.html) to learn more about embedding a time series within a tibble. 



## Test Your Understanding

1. The output of the following code is equivalent to a factor with the letters "a" to "f".

``` r
(abc <- factor(letters[1:3]))
#> [1] a b c
#> Levels: a b c
(def <- factor(letters[4:6]))
#> [1] d e f
#> Levels: d e f
c(abc, def)
```

2. The output of the following code is a date object.

```r

library(lubridate)

date <- ymd("2020-10-13")

dt <- ymd_hms("2020-10-13 09:30:00")

c(date, dt)

```

## Demonstration

- Demonstrate lubridate (not on worksheet): 
    - `ymd()` family of functions to convert text to a date (not in worksheet).
    - Getting components of a date object with things like `yday()`, `year()`, and `wday()`.
- Work on Worksheet A5 (factors and dates portion)