---
title: "Manipulating Data with dplyr"
output: html_document
---

## Learning Objectives

From this topic, students are anticipated to be able to:

1. Use the five core dplyr verbs for data wrangling: `select()`, `filter()`, `arrange()`, `mutate()`, `summarise()`.
2. Use piping when implementing function chains.
3. Use `group_by()` to operate within groups (of rows) with `mutate()` and `summarise()`. 
4. Use `across()` to operate on multiple columns with `summarise()` and `mutate()`.

We will spend roughly two lectures on this topic.

## Resources

Video lectures for this topic (ignore the episode numbering):

- [dplyr Part 1: Basic Data Manipulation](https://youtu.be/Gms3zSPqCk8)
- [dplyr Part 2: Calculations on tibbles](https://youtu.be/38BA_v7BwKk)

Optional further reading for the dplyr verbs and piping, minus the `across()` function:

- [Chapter 6](https://stat545.com/dplyr-intro.html) and [Chapter 7](https://stat545.com/dplyr-single.html) of Jenny Bryan's STAT 545 book follows along with what we will be covering in Day 1 and Day 2 of this topic (although you won't find the `across()` function).
- "R for Data Science" is another great resource for learning data wrangling. Take a look at:
    - [R4DS Data Transformation](https://r4ds.had.co.nz/transform.html) for the dplyr verbs (without `across()`)
    - [R4DS Pipes](https://r4ds.had.co.nz/pipes.html) for more on piping.
- [dplyr's introductory vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html) is useful for orienting you to the package. 

Optional further reading to learn about the `across()` function:

- [Hadley Wickham's blog post on the topic](https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-colwise/).

## Test Your Understanding

1. True or False? Running filter or select on your tibble permanently changes your tibble. 
2. True or False? The pipe operator `%>%` works for functions outside of the tidyverse, too.
3. `summarise()` reduces each group down to one row, and `mutate()` preserves the number of rows. But, between the two, there's a way to reduce each group down to _two_ rows.
4. `across()` doesn't allow you to make new column names. 

## Demonstration

We will go through Worksheet A2 ([.ipynb](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/worksheets/worksheet_a02.ipynb); [viewable](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/content/worksheets/worksheet_a02.ipynb); [zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/raw/master/content/worksheets/worksheet_a02.ipynb.zip)) in class. (Due Saturday, Sept 25, 2021 at 22:00 PT)