---
title: "Websites/Slides"
output: html_document
---

One great thing about having html files output from Rmd? We can use Rmd as a framework for creating websites, because websites are often just html. 

Similarly, we can use Rmd as a framework for creating pdf slides (through the Beamer LaTeX document class) or html slides (through reveal.js).

This is especially powerful when you move to the *next generation* version of Rmd, [Quarto](https://quarto.org/). 

Note that Quarto was released in 2022, so there are still some growing pains. But it seems to be the way of the future for websites and slides, so it's what we'll cover. 

This topic is optional. It will probably also be short.  

## Quarto Installation and Basics 

Official tutorial [here](https://quarto.org/docs/get-started/hello/rstudio.html). It's very straightforward to pick up if you already know Rmd. (Which we do!) 

## Quarto Websites 

Official tutorial [here](https://quarto.org/docs/websites/). See [Quarto's Gallery](https://quarto.org/docs/gallery/) for a variety of sample output formats, such as presentations, websites and reports. Here is an example of a Quarto website from a workshop I collaborated on for creating and distributing R packages: [SSC Workshop 2024](https://ubc-stat.github.io/ssc-workshop-2024/). Also see [this slide deck by Lucy Gao](https://www.dropbox.com/s/fit9xfhndr79w6m/2023-StudentSeminar.pdf) on building a professional online presence for why you should have a website **right now**. 

Once you've built a website (collection of html files), you will need to **host it** somewhere on the internet. Our recommendation is [Github Pages](https://pages.github.com/) or [Netlify](https://www.netlify.com/) because they're free. 

## Quarto Slides 

Official tutorial [here](https://quarto.org/docs/presentations/). An example of a Quarto slide deck is [Lucy's guest lecture in STAT 540](https://stat540-ubc.github.io/lectures/lect16-clustering/lect16-clustering-guest.html). This uses our preferred format, [reveal.js](https://revealjs.com/). You can download the slide deck WITH the source [here](https://www.dropbox.com/s/aataltxawu2qxn3/lec14-clustering.zip?dl=0). This is a great way to make your slide deck *reproducible*. 

