---
title: "List Columns"
output: html_document
---

Did you know that a column of a tibble can contain a list -- not just a vector? This week explores when such a thing would come in handy, and how to work with list columns. 

From this topic, students are anticipated to be able to:

- Use the `map` family of functions from the purrr package to iteratively apply a function.
- Create and operate on list columns in a tibble using `nest()`, `unnest()`, and the `map()` family of functions.
- Define functions on-the-fly within a `map` function using shortcuts.
- Apply list columns to cases in data analysis: columns of models, columns of nested lists (JSON-style data), and operating on entire groups within a tibble. 

## Resources

Video lectures:

- [Vectors and Lists in R](https://www.youtube.com/watch?v=nJgrDoCENBI)
- [R List Columns: purrr map and nesting](https://www.youtube.com/watch?v=_731PZ8I9m0)

Written material:

- [R4DS Chapter 21: Iteration](https://r4ds.had.co.nz/iteration.html) for purrr
    - 21.1 for an intro
    - 21.5 for the `map` family of functions
    - The intro of 21.7 for the `map2` and `pmap` families.
- ["List Columns"](https://jennybc.github.io/purrr-tutorial/ls13_list-columns.html) from [Jenny's purrr tutorial](https://jennybc.github.io/purrr-tutorial/index.html)
- ["Nested data" article](https://tidyr.tidyverse.org/articles/nest.html) on tidyr's website.

Want to dig deeper? These resources can help.

- [Advanced R Chapter 9: Functionals](https://adv-r.hadley.nz/functionals.html) -- looking at purrr and `map()` from a programming perspective. 
- [tidyr's rectangling vignette](https://tidyr.tidyverse.org/articles/rectangle.html) -- for handling deeply nested lists (JSON-style data), similar to tidyr's `pivot_` functions. 

## Test Your Understanding

1. True or False: `map(1:3, ~ function(x) x ^ 2)` returns the list `list(1, 4, 9)`.
2. You write a function `square()` that squares its input -- but the first thing it does is print a message to the screen! True or False: `map_dbl(1:10, square)` will throw an error, because the output is not a `dbl` (a number) -- it contains the message, too.
3. True or False: purrr-style functions, starting with `~`, can be used in dplyr's `across()` function, such as `mutate(across(where(is.numeric), ~ .x ^ 2))`, and this function can only take one argument (`.x`)
4. True or False: If I have 10 tibbles I want to save to file, and they're all stored in a list, the best purrr function to use for saving these to file is `map()`.
5. True or False: Just as `c(c(1, 2), c(3, 4))` returns the vector of numbers from 1 to 4, `list(list(1, 2), list(3, 4))` returns the list of numbers from 1 to 4. 
6. True or False: `tibble(model = lm(mpg ~ wt, data = mtcars))` doesn't work because it doesn't use a `map` function.

## Demonstration

Why use the `map` functions over `for` loops? Aside from what's said at [R4DS's Section 21.4](https://r4ds.had.co.nz/iteration.html#for-loops-vs.-functionals), the `map` family encourages the input vector(s) and function to be carefully defined first, whereas a `for` loop is more of a free-for-all. Using `map()` is also more readable, is pipe-friendly, and jibes well with list columns in tibbles. 

Let's jump right into the worksheet for this topic. 


