---
title: "Shiny Apps"
output: html_document
---

This topic aims to provide you with a foundation for making a shiny app. From this topic, students are anticipated to be able to:

- develop the user interface of a shiny app from scratch,
- develop interactivity using widgets in a shiny app,
- deploy a shiny app to shinyapps.io,
- create interactive Shiny R Markdown documents (embed shiny features within an Rmd file).

And possibly:

- Make an interactive plot with plotly
- Make an interactive data table with the `DT` package

## Resources

Video lecture:

- [How to Make a Shiny App in R](https://www.youtube.com/watch?v=rB4SJGyaGls)

Written material:

- [Dean Attali's shiny tutorial](https://deanattali.com/blog/building-shiny-apps-tutorial/) (which forms the basis from which our STAT 545 tutorial was created).
- ["Mastering Shiny"](https://mastering-shiny.org/) by Hadley Wickham gives a more comprehensive treatment.  
- The [official shiny site](https://shiny.rstudio.com/) has tutorials, a gallery, and other goodies.

Regarding specific tasks:

- For deploying shiny apps, check out [https://www.shinyapps.io/](https://www.shinyapps.io/)
- For shiny documents (= R Markdown + shiny), see [Chapter 19 of Yihui’s R Markdown book](https://bookdown.org/yihui/rmarkdown/shiny-documents.html).
- For testing your shiny app, check out the [shinytest](https://rstudio.github.io/shinytest/) and [reactlog](https://github.com/rstudio/reactlog) packages. 
- For further cutting down on code repetition by "functionizing" your shiny app, check out [Emily Riederer's beginner's guide to Shiny modules](https://emilyriederer.netlify.app/post/shiny-modules/) for a gentle introduction and [Chapter 19 of the "Mastering Shiny" book](https://mastering-shiny.org/scaling-modules.html) for a full treatment.



Other dashboard tools besides shiny (but not in R):

- With python: plotly dash. Check out the [main website](https://plotly.com/dash/), or [this Medium post](https://medium.com/plotly/introducing-dash-5ecf7191b503) introducing the tool.
- With javascript: [D3](https://d3js.org/), a tremendously powerful tool with a steep learning curve (esp. if you don't know javascript).

## Test Your Understanding

1. True or False: A shiny app, as a website, still requires an instance of R running in the background. The stat545.stat.ubc.ca website is static: it doesn't require an active session to be running in the background.
2. True or False: Although it's important to document both a shiny app and an R package, documentation is more important in R packages compared to shiny apps.
3. True or False: The following code ordinarily has `y` as 15, but using `shiny::reactive()` in a shiny app can have `y` equal `11`.
   ```
   x <- 10
   y <- x + 5
   x <- 1
   ```
4. True or False: Since shiny's UI is html, we can manually write the UI by writing HTML in the `HTML()` function. 

## Demonstration

Before we begin, know that __this resource is a bare-bones checklist__ optimized for instructional purposes, and is not designed as a step-by-step walkthrough for learning shiny. For that, you should see the more detailed [stat545.com shiny chapter](https://stat545.com/shiny-tutorial.html) or [Dean Attali's tutorial](https://deanattali.com/blog/building-shiny-apps-tutorial/) -- both are very similar. 

### Introducing shiny

Motivation for shiny: explore the [shiny user showcase](https://shiny.rstudio.com/gallery/#user-showcase):

- [ ] First, let's find a "shiny demo"
- [ ] Then, a "shiny user showcase".

The code behind a shiny app has the following layout in a file called `app.R` -- development involves filling in the `FILL_THIS_IN` parts:

```
library(shiny)

ui <- fluidPage(FILL_THIS_IN)

server <- function(input, output) {
    FILL_THIS_IN
}

shinyApp(ui = ui, server = server)
```

There is also a two-file option if you'd like, defining the `ui` object in `ui.R`, and the `server` object in `server.R`.  

### Exploring the RStudio Boilerplate

Open the boilerplate:

1. [ ] File > New File > Shiny Web App...
2. [ ] Ensure "Single File" is selected, and choose a directory.

What R objects are `ui` and `server`? What are they meant for?

- `ui` is HTML; `server` is a function.
- `ui` is for the display; `server` holds the R machinery.

Side-by-side comparison between the launched app and the code:

- Notice the layouts: `sidebarLayout()`, `titlePanel()`.
- Notice the widget code, and the placeholder for a plot.
- Notice that calculations (and more familiar R code) go in the `server`.
- Notice that we _define_ the (list-like) `output` argument, and _use_ the (list-like) `input` argument. 
- Notice that additions to `ui` are _function arguments_, and additions to `server` are new lines (specifically: lines that define things).

### Making the BCL Shiny App

Get set up:

1. [ ] Start from scratch -- try the above template containing the `FILL_THIS_IN` fields.
2. [ ] BCL Data: 
    a. [ ] Download the [data](https://deanattali.com/files/bcl-data.csv); place alongside `app.R`.
    b. [ ] Load the tidyverse.
    c. [ ] Read in the data above `ui` with `bcl <- read_csv("bcl-data.csv")`
3. [ ] Include `options(shiny.autoreload = TRUE)` so that I can see the changes appear instantly. 

Add a plot to the app:

1. [ ] Verify that calling ggplot2 in the `ui` won't work. Why not? Think coercion. 
2. [ ] Instead of trying to place the plot directly in `ui`, make a _placeholder_ for the plot: `plotOutput()`.
    - Always needs an ID (first argument): this will be the link between `server` and `ui`.
3. [ ] Render the plot in the `server`, and link it to the placeholder:
    a. [ ] As if `output` is a list, make an entry named by the plot ID. Try setting this to the plot itself -- doesn't work. Plot code:
    ```
    ggplot(bcl, aes(Alcohol_Content)) +
      geom_histogram()
    ```
    b. [ ] Wrap plot in `renderPlot()` function.
    c. [ ] Improve formatting: allow for the possibility of multiple lines with `{}`.

Add interactivity to the plot via a slider:

1. [ ] Add a slider to the `ui` with `sliderInput()`. 
    a. [ ] Add arguments to allow a user select a price range between 0 and 100. All `*Input()` functions require: 
        - an ID (to communicate between `ui` and `server`)
        - a label (text to appear with the widget)
        - All other arguments are specific to the widget. Hint: `value` should be a vector; use `pre = "$"`.
    b. [ ] Check out [other widgets](https://shiny.rstudio.com/tutorial/written-tutorial/lesson3/) (from the official Shiny tutorial)
2. The (list-like) `input` argument in `server` now has an entry named by the widget ID:
    a. [ ] Investigate the contents of this list entry using this trick: `print()` it to screen in your `renderPlot()` function. Where does it print to screen? Less hacky method: use the `observe()` function instead, top level of function.
    b. [ ] Use this list entry to filter the `bcl` data.
3. [ ] Try adding another widget to further filter the data: `radioButtons()`.
    - Use `choices = c("BEER", "REFRESHMENT", "SPIRITS", "WINE")`

Improve the user interface:

1. [ ] Add a `titlePanel()`. What's the output of `titlePanel()`?
2. [ ] Add a `sidebarLayout()` with a `sidebarPanel()` and `mainPanel()`. What should go where?
3. [ ] Add some description to the app -- maybe some welcome text.
    a. [ ] Try raw text
    b. [ ] Try headers with `h1()`, `h2()`, etc; bold with `b()` from the `tags` object; and a link to Dean's original BCL app with `a(href = "https://github.com/daattali/shiny-server/tree/master/bcl", "TEXT_HERE")` 
  
Display a table of the BC Liquor data below the plot:

1. [ ] Use `renderTable()` and `tableOutput()`.

Data filtering happens twice. Use reactive programming to prevent duplicated code:

1. [ ] Gotcha #1: Try saving the filtered data in the `server()` function as a new variable. Does it work?
2. [ ] Make it work by wrapping the `reactive()` function.
3. [ ] Gotcha #2: Can you refer to the variable you made by name? No. Treat it as a function with no arguments by appending `()`.

### Taking shiny further

Want to do more with shiny? Let's explore these features, although we won't implement them.

1. [Mouse-based interaction with plots](https://shiny.rstudio.com/articles/plot-interaction.html): use arguments of `plotOutput()`. 
    - See the example at the bottom of the above page.
    - Notice: no widget, but instead, ID given for `click`, `dblclick`, `hover`, or `brush` arguments of `plotOutput()`.
2. Create dynamic UI components ([RStudio tutorial](https://shiny.rstudio.com/articles/dynamic-ui.html); [stat545.com basic example](https://stat545.com/shiny-tutorial.html#basic-example-of-uioutput))
    - Try out the stat545.com example.
    - Notice `uiOutput()` and `renderUI()`, as per normal, except this time `sliderInput()` is in the `renderUI()` function in the `server` object, not the `ui`.
3. [Change the theme](https://rstudio.github.io/shinythemes/) (colour palette, font, etc) of your shiny app using the `shinythemes` package.
4. Make a shiny app look like a website, complete with tabs and pages, using the `shinydashboard` package -- [getting started page](https://rstudio.github.io/shinydashboard/get_started.html). Notice:
    - Uses `dashboardPage()` instead of `fluidPage()` for UI.
    - Tabs link to separate pages: a `menuItem()` within a `sidebarMenu()` is linked to a page defined in `tabItem()`, linked via `tabName`.
    - Tabs without shinydashboard: use `navbarPage()` or `tabsetPanel()`.
5. Deploy your apps for free to shinyapps.io -- click the "publish" button in RStudio, and follow the instructions. Notes:
    - shinyapps.io limits: free version
    - Requires R to run in the background, so can't just be any host.
6. Make shiny documents / Interactive documents (Rmd). Learn more from [Chapter 19: Shiny Document](https://bookdown.org/yihui/rmarkdown/shiny-documents.html) from the "R Markdown" book by Yihui Xie et al.
    - Load the RStudio boilerplates (presentation and html): File > New File > R Markdown... > Shiny
    - Notice:
        - The `runtime: shiny` in the YAML header. 
        - The addition of a widget with an `*Input` function like `sliderInput()`.
        - The addition of a plot with `renderPlot()`.

Interactivity without shiny:

1. Make navigable data tables from the DT package. *HTML output does not require an R instance to be running!*
    - Wrap a tibble / data frame in `DT::datatable()` in an Rmd file, and knit.
2. Make interactive plots with plotly (an R package, but primarily [exists as a javascript graphing library](https://plotly.com/javascript/)). *HTML output does not require an R instance to be running!*
    - Browse around some plots in the above link.
    - Quick win: wrap a ggplot object with the `plotly::ggplotly()` function.
    - Make a plotly plot from scratch with `plot_ly()`