---
title: "Tidy Data"
output: html_document
---

From today's class, students are anticipated to be able to:

- recognize whether a given dataset is 'tidy' or 'untidy'
- convert a dataset between the 'long' and 'wide' format, using `tidyr::pivot_longer()` and `tidyr::pivot_wider()`
- assess which format is best suited for each type of analysis
- deal with missing data in a tibble

## Resources

Video lecture for this topic:

- [tidyr for Pivoting and Tidy Data](https://youtu.be/qivE6exNsZI)

Written resources on tidy data:

- To learn how to use the `pivot_*()` functions, consult tidyr's [pivot vignette](https://tidyr.tidyverse.org/articles/pivot.html).
- To get a better understanding of the concept of tidy data:
    - Hadley Wickham's [paper on Tidy Data](https://vita.had.co.nz/papers/tidy-data.pdf) is the gold standard treatment of tidy data.
    - A "code heavy" version of the tidy data paper is tidyr's ["Tidy Data" vignette](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html).

## Test Your Understanding

1. True or False: it's possible to lengthen a tibble "all the way" so that it can't be lengthened anymore.
2. True or False: To make a scatterplot viewing the relationship of Africa's GDP per capita vs. Europe's, use `pivot_wider()`. 

## A note on deprecated functions: `spread()` and `gather()`

Pivoting used to be achieved through the tidyr `spread()` and `gather()` functions. These are now deprecated and should not be used. They are only kept along with the tidyr package for backward compatibility. 

## Demonstration

We will be going through Worksheet A-4 in class. 