---
title: "Lecture Notes: Plotting Part I"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
knitr::opts_chunk$set(fig.width = 5, fig.height = 3, 
                      fig.align = "center", error = TRUE)
```

## Learning Objectives

From this topic, students are anticipated to be able to:

+ Identify the seven components of the grammar of graphics underlying ggplot2.
+ Recognize the advantages of ggplot2 over plotting with base R and lattice.
+ Use different geometric objects and aesthetics to explore various plot types.

## Resources

Video lecture for today (ignore the episode numbering):

- [ggplot2 Part 1: Introduction to Plotting](https://youtu.be/cqcQT44mJTM)

Optional further reading:

- As in last time, the "R for data science" book is a great resource. For today's class, we suggest following through sections 3.1 to 3.4 of the [R4DS Data Visualization](https://r4ds.had.co.nz/data-visualisation.html) chapter.
- For a comprehensive look into ggplot2, it's worth reading Hadley Wickham's [ggplot2 book](https://ggplot2-book.org/).
- If you need a quick lookup, consider:
    - The [ggplot2 cheatsheet](https://github.com/rstudio/cheatsheets/blob/master/data-visualization-2.1.pdf) (Also available through RStudio: "Help" -> "Cheatsheets" -> "Data visualization with ggplot2").
    - [R Cookbook Graphs](http://www.cookbook-r.com/Graphs/) 

## Quiz

1. True or False: You can re-specify global aesthetics by adding an aes() layer to a ggplot object. 
2. True or False: With ggplot2, we can specify the data in a geom layer, in addition to the initial ggplot() layer.

## Demonstration

+ In-class demo of creating a scatterplot (~10 minutes)
+ Why data visualization? Just plot it + The grammar of graphics (~10 minutes)
  





