---
title: "Assignment B-4"
output: html_document
---

__Total Points__: 100

For this assignment, you will pick one of three options described below.

+ **Option A:** Strings and/or Functional Programming
+ **Option B:** R Package 
+ **Option C:** Shiny App

## Submission Instructions

It is **very important** that you submit a link to your work on canvas. If not, we won't be able to find your work, because each option involves working in a different repository.

The link you provide should link to a tagged release in your assignment repository, corresponding to the point in time of your repository's life that we should be grading. 

## Tidy Submission

RRR: Code runs without errors and it is appropriately annotated, legible, and easy to follow.

Proper English, spelling, and grammar. 

## Option A -- Strings and functional programming in R

Complete **2 of the following 3** exercises using concepts and tools covered in class (i.e. `stringr`, `purrr`, regex, tidyverse, etc.)

**Setup**: Make a new repository if you're going with this option, by clicking the link provided to you on canvas. Name the repository as you wish. 

### Tidy Submission (2 points)

Two points are set aside for a tidy submission, as per previous assignments. You choose where you want to answer these questions -- just make this clear in your Assignment 5-B README file. You don't need to update your Makefile accordingly for this assignment (but we suggest you give it a try).

Code should adopt a consistent and easy-to-read style -- ideally, the [tidyverse style](https://style.tidyverse.org/), although we're certainly not looking for strict adherence. 

### Exercise 1 (9 points)

Take a Jane Austen book contained in the `janeaustenr` package, or another book from some other source, such as one of the many freely available books from [Project Gutenberg](https://dev.gutenberg.org/) (be sure to indicate where you got the book from). Make a plot of the most common words in the book, removing "stop words" of your choosing (words like "the", "a", etc.) or stopwords from a pre-defined source, like the `stopwords` package or `tidytext::stop_words`. 

If you use any resources for helping you remove stopwords, or some other resource besides the `janeaustenr` R package for accessing your book, please indicate the source. We aren't requiring any formal citation styles, just make sure you name the source and link to it. 


### Exercise 2 (9 points)

Make a function that converts words to your own version of Pig Latin. 

The specific input and output that you decide upon is up to you. Don't forget to implement good function-making hygiene: we'll be looking for documentation (being sure to describe your Pig Latin conversion), examples of applying the function, 3 non-redundant tests, appropriate use of arguments, and appropriate amount of checking for proper input.

Your Pig Latin should incorporate two components:

**Rearrangement component** 

The default Pig Latin rearrangement rule, [as per Wikipedia](https://en.wikipedia.org/wiki/Pig_Latin#Background), moves beginning letters to the end:

> 1. For words that begin with consonant sounds, all letters before the initial vowel are placed at the end of the word sequence.
> 2. When words begin with consonant clusters (multiple consonants that form one sound), the whole sound is added to the end
> 3. For words beginning with vowel sounds, one removes the initial vowel(s) along with the first consonant or consonant cluster.

Modify this somehow. Maybe you move letters from the end to the beginning, or you change the rules altogether, keeping a similar level of complexity.

**Addition component**

The default Pig Latin addition rule is to add "ay" to the end of the word, after rearranging the letters of the word. You should choose some other addition rule.

### Exercise 3

| Rubric | Description | Points |
|--------|-------------|--------|
| First map | First `purrr` mapping function was used correctly | 2 |
| Second map | Second `purrr` mapping function was used correctly | 2 |
| (Un)nesting | Was done appropriately | 2 |
| Explanation | What was claimed to be calculated was indeed calculated | 2 |

For this exercise, you'll be evaluating a model that's fit separately for each group in some dataset.

Examples:

- Maybe your model is a linear model (using `lm()`) for each continent in the `gapminder::gapminder` dataset.
- Maybe your model is a distribution of a single variable (using the [`distplyr` package](https://distplyr.netlify.app/)) for each penguin in the `palmerpenguins::penguins` dataset.

Your tasks are as follows.

1. [ ] Make a column of model objects. Do this using the appropriate mapping function from the `purrr` package.  Note: it's possible you'll have to make use of nesting, here. 
    - For `distplyr`, use a `distplyr::dst_*()` function of your choosing, like `dst_norm()` or `dst_step()`. Note that there aren't that many `dst_*()` functions yet, sorry -- `distplyr` is still quite young.
2. [ ] Evaluate the model in a way that interests you. But, you should evaluate something other than a single number for each group. Hint: you'll need to use another `purrr` mapping function again.
    - For `distplyr`, use a distributional representation of your choosing, such as quantiles, using the appropriate `distplyr::enframe_*()` function.
3. [ ] Print out the tibble so far. 
4. [ ] Unnest the resulting calculations, and print your final tibble to screen. Make sure your tibble makes sense: column names are appropriate, and you've gotten rid of columns that no longer make sense. 



## Option B -- R package

For this option, you will be updating your package to a new version, or creating an entirely new R package from scratch if you prefer. 

**Setup**: No setup required; just use the same repo you used for your R Package. 

This time, we will be evaluating the *quality and overall design* of your R package, not just that you can create one. That means, not only do you need all of the components of a working R package, the quality of the components themselves will be expected to be of high quality. We will also evaluate the overall cohesiveness and design of the package.

Whereas the previous assignment 2b focused on component additions evaluated by functionality (such as components of an R package being present and functional, or having added 3 functional features), this time we will evaluate how well your product forms a complete whole, satisfying a clearly stated purpose with an effectively designed interface ("interface" being how a user interacts with the product).

If you have decided to build onto assignment 2, this might mean you don't need to add anymore functionality, just improve the existing components of your package!

Feel free to start a new R package if you are not interested in building on assignment 2b. However, keep in mind that most of the requirements for assignment 2b are also required here. 

If you have decided to build onto assignment 2b, then be sure to have a properly tagged release and version number for assignment 2b, so that we can easily see the new changes you've implemented for assignment 5b. If there was a problem with versioning, or you originally had forgotten to do this, just tag a release now before you start, and clearly indicate this in the README or in canvas.

#### How to implement package updates

1. Create changes to your R package that you plan to address in this updated version. If appropriate, describe the improvements using *Github Issues*. Consider also taking advantage of *Git Branches* to group sets of related changes.

  **Any feedback that was given on your assignment 2b needs to be addressed!** If addressing TA feedback, it would be in good practice to *respond to the Github Issue containing the feedback* :) 

2. _**Address each issue**_, while also ensuring that your R package still "works". It should "check" without errors. 

3. _**Create a pull request (or multiple, if appropriate)**_, comment and describe how each issue was addressed. Make sure you reference the issues with the appropriate hashtag, and also reference new files or lines of code when appropriate. 

5. _**Merge pull request(s) and update to an appropriate version number**_. Also ensure that all documentation (including version number in `DESCRIPTION`) is updated. Don't forget to update `NEWS.md`. See [here](https://r-pkgs.org/release.html#release-version) for help on deciding version numbering.

#### Option B - Rubric

**Basic structure and functionality (2.5 points)**

Following assignment 2b instructions and rubric may be helpful for completing this

- [ ] Do you have all essential components for your R package? 
  - [ ] All functions have tests
  - [ ] All functions and data have documentation
  - [ ] If data was included, did you include how the data was sourced?
  - [ ] DESCRIPTION has correct information
  - [ ] If your package is a data package, do you have a vignette?

**Code Mastery (5 points)**

- [ ] (3 points) Is your code written efficiently?
  - [ ] Did you use tidyverse when appropriate?
  - [ ] Is your code easy to understand? Did you write code comments when appropriate?
- [ ] (2 points) Are your tests good quality?

**Package design (7.5 points)**

- [ ] (2.5 points) Does your package have a clear and consistent purpose?
  - [ ] Functions and data make sense to be packaged together
  - e.g. `ggplot2` is a package all about plotting
  
- [ ] (2.5 points) Do package functions and data have user-friendly design?
  - Function arguments make sense
  - Data is organized appropriately and can be easily accessed
  - Documentation is helpful and complete
  
- [ ] (2.5) README and vignette is helpful
  - Purpose of package is clearly described
  - Functions and datasets are demonstrated
  - Examples should be easy to be run by users
  - *If developing a data package*, more weight will be put towards a providing a good quality vignette that showcases the data
  
- [Writing is clear](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_writing.md).

**Package development (5 points)**

- [ ] Did you develop your R package in a robust way, using `usethis` and `devtools`?
- [ ] Did you use Github Issues, branches, and pull requests in an appropriate manner? 
- [ ] Did you address all errors from running `check()`?
- [ ] Did you tag releases and update version numbers appropriately?

#### Submission

- [ ] 

- [ ] In canvas, provide the tagged release to your assignment repository.

## Option C -- Shiny App

For this option, you will be implement additional features and improvements to your shiny app that you worked on in Assignment 3b, or creating an entirely new shiny app from scratch. This time, we will be evaluating the *quality and overall design* of your shiny app. 

**Setup**: No setup required. Just use the same repo you used for your shiny app. 

#### Before you start

**If you are building onto assignment 3b shiny app,**

Ensure that your assignment 3b shiny app is deployed and viewable on [shinyapps.io](). We will use this as a reference to mark your improved version. Start by copying over your app (code and any data files) to an Assignment 5b folder. Complete this assignment by editing this version of your app. When finished deploy this on [shinyapps.io]().

**If you are starting a new app from scratch,** state so in the assignment 5b README.

#### Requirements

If you are building onto assignment 3-B, after addressing feedback, you should have three working features implemented. If you are starting from scratch, you'll need to produce the equivalent of Assignment 3-B (i.e. have three working features) before moving on.

You might find that to satisfy some of these requirements, new features will have to be implemented.

**App design**

This time we will be evaluating the overall app design. Your app should have a clearly defined purpose and function accordingly. The way the user interacts with the app is another important design decision. It should be easy for the user to both understand how the app is supposed to be used and also for the user to use the app. 

**Code mastery**

Ensure that your code is of high quality. This means that a minimal amount code and dependencies are used (code efficiency). We will also look for appropriate usage of shiny-specific concepts, such as reactive expressions. 

#### Option C - Rubric

**3 features are implemented (5 points)**

- [ ] After addressing assignment 3b feedback, you should have 3 functional features
- [ ] If starting from scratch, you have at least 3 working features

**User friendly design (5 points)**

- [ ] Is it easy for users to understand how to engage with the app?
- [ ] Were chosen widgets appropriate for each type of input? 
- [ ] Is the writing clear?
- [ ] Does the layout make sense?

**Code quality (5 points)**

- [ ] Code is efficient
- [ ] Reactive expressions used appropriately
- [ ] `tidyverse` used when appropriate
- [ ] Code comments are appropriately used
- [ ] Only essential R packages are loaded

**Design and functionality (5 points)**

- [ ] The purpose of the app is clearly indicated
- [ ] The functioning of the app adequately achieves the purpose
- [ ] There's enough documentation to know how to use the app. Ideally, one doesn't *have* to read all that much to use the app at a superficial level.





#### Submission



Update your assignment repo READMEs with the appropriate [shinyapp.io]() links. 
