---
title: "mini-project-2"
author: "Victor Yuan"
date: "22/09/2020"
output: html_document
---

# Welcome back to your mini data analysis project!

This time, we will explore more in depth into your research questions that you defined in milestone one. 

Begin by loading your data and the tidyverse packagebelow: 

```{r}
library(datateachr) # <- contains the data you picked!
library(tidyverse)
```

# Learning Objectives

By the end of this milestone, you should:

+ Become familiar with manipulating and summarizing your data in tibbles using `dplyr`
+ Understand how to use investigate research questions using `dplyr`
+ Generate a reproducible and clear report using R Markdown

# Task 1: Process and summarize your data (15 points)

**Things to keep in mind**

+ Remember to document your code, be explicit about what you are doing, and write notes in this markdown document when you feel that context is required. Create your analysis as if someone else will be reading it! 

+ Before working on each task, you should always keep in mind the specific **research question** that you're trying to answer.

From milestone 1, you should have an idea of the basic structure of your dataset (e.g. number of rows and columns, class types, etc.). Here, we will start investigating your data more in-depth using various `dplyr` functions. 

1.1 First, write out the 4 research questions you defined in milestone 1 were. This will guide your work through milestone 2:

1. *FILL_THIS_IN*
2. *FILL_THIS_IN*
3. *FILL_THIS_IN*
4. *FILL_THIS_IN*

1.2 Now, for each research question, complete 1 of the 10 operations described below. **Keep in mind that some of these will make more sense than others, depending on the research question!** For each of your chosen operation, you should explain why this operation *makes sense* and why the output helps answer the corresponding research question. Ensure that the output of each operation is printed! 

Options:
1. Group your tibble by one variable of your choosing with `dplyr::group_by()`, and then return the range (i.e. minimum and maximum) of a second variable using `dplyr::summarize()`.
2. Group your tibble by one variable, then return the mean and standard deviation of a second variable.
3. Using `dplyr`, for a categorical variable, find the number of rows in each group. Don't use the function `table()`!
4. Remove all rows with missing observations (i.e. `NA`s). Show the number of missing observations before and after this task.
5. Filter out >1 row based on a criteria of your choice.
6. For a numeric variable in your dataset, convert it into a different unit of measurement (e.g. length in inches into centimeters, kilometers into miles, hours into minutes).
7. After grouping by one variable, arrange your tibble by a second variable.
8. Give a variable a better name! Why is it better?
9. Rename a variable by making it [snake case](https://en.wikipedia.org/wiki/Snake_case), if it's in [camel case](https://en.wikipedia.org/wiki/Camel_case), or vice versa. Why is it better?
10. Remove 1 or more columns, then rearrange the remaining columns in a way that makes sense.

You should have one operation for each of your 4 research questions!

<!-- Start your work below -->


<!-- End of your work -->

1.3 Based on the operations that you've completed, how much closer are you to answering your research questions? Think about what aspects of your research questions remain unclear. Can your research questions be refined, now that you've investigated your data a bit more? 

# Task 2:  (15 points)

If we rewind and go back to the learning objectives, you'll see that by the end of this deliverable, you should have formulated *4* research questions about your data that you may want to answer during your project. However, it may be handy to do some more exploration on your dataset of choice before creating these questions - by looking at the data, you may get more ideas. **Before you start this task, read all instructions carefully until you reach START HERE**.

2.1 Complete *4 out of the following 8 exercises* to dive deeper into your data. All datasets are different and therefore, not all of these tasks may make sense for your data - which is why you should only answer *5*. Use *dplyr* and *ggplot*.

1. Plot the distribution of a numeric variable.
2. Create a new variable based on other variables in your data (only if it makes sense)
3. Investigate how many missing values there are per variable. Can you find a way to plot this?
4. Explore the relationship between 2 variables in a plot.
5. Filter observations in your data according to your own criteria. Think of what you'd like to explore - again, if this was the `titanic` dataset, I may want to narrow my search down to passengers born in a particular year...
6. Use a boxplot to look at the frequency of different observations within a single variable. You can do this for more than one variable if you wish!
7. Make a new tibble with a subset of your data, with variables and observations that you are interested in exploring.
8. Use a density plot to explore any of your variables (that are suitable for this type of plot).

2.2 For each of the 4 exercises that you complete, provide a *brief explanation* of why you chose that exercise in relation to your data (in other words, why does it make sense to do that?), and sufficient comments for a reader to understand your reasoning and code.

# Task 3: Write your research questions (5 points)

So far, you have chosen a dataset and gotten familiar with it through exploring the data. Now it's time to figure out 4 research questions that you would like to answer with your data! Write the 4 questions and any additional comments at the end of this deliverable. These questions are not necessarily set in stone - TAs will review them and give you feedback; therefore, you may choose to pursue them as they are for the rest of the project, or make modifications!

<!--- *****START HERE***** --->

