# STAT 545A Assignment 01: Tools for data analytic work

__Due September 17, 2019 at 23:59__

## Objective

This assignment was designed to give you practice with the tools discussed in the first two weeks: GitHub, R, (R) Markdown, and git. You'll be:

- Developing of a simple repository with GitHub; perhaps git too
- Authoring in GitHub-flavoured markdown and R markdown
- Coding in R through data exploration
- Generating output from (`.Rmd`) source

using RStudio.

As you work on the assignment, you are welcome to work from the browser (i.e., directly on GitHub), but we encourage you to pilot a more powerful workflow:

- Pull from GitHub (just an empty precaution now, but will matter when you collaborate with others).
- Make changes locally to local files -- RStudio is a great Markdown editor! Click Preview to see how it's going to look!
- Save your changes.
- Commit your changes to your repo.
- Push the commit to GitHub.

## Tidy Submission (10%)

#### Mechanics (5%)

- Your submission should be self-contained in a folder within your STAT 545A homework repository (found in [the hw Org](https://github.com/STAT545-UBC-hw-2019-20)).
- Your work must be reproducible from beginning to end. That is, a member of the teaching team should be able to run all code error-free and reproduce the output files. 
- Your scripts do not contain code that installs packages (this is not good practice anyway) – note that this is different from loading packages with the `library()` function, which is good!
- Your submission for this assignment should be in its own folder in your homework repository. (Special case for Assignment 01: your repo's `README.md` file should not be in this folder).
- All R Markdown files are `knit`ted to an output readable on GitHub (probably `github_document` or `pdf_document`).
- You followed the assignment submission instructions.

If there's any further uncertainty in determining a grade for this "mechanics" portion, the [UBC MDS mechanics rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_mech.md) will be referred to.

#### Writing (5%)

- You must use proper English, spelling, and grammar.
- You should write concisely. 

If there's any further uncertainty in determining a grade here, the [UBC MDS writing rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_writing.md) will be used.

## Edit `README.md` (35%)

---

Rubrics: 

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md): (15%)
	- Does your markdown render properly, or are there mistakes like _this__ or (this)[www.example.com]?
- completeness: (20%)
	- Did you include at least five markdown features in your README? (= 4% each)

---

Your task here is to edit the main `README.md` file in your repository to contain a sampler of GitHub-flavoured markdown features.

The beginning of the README should contain a very brief description as to what the repository is, so that an unknowing visitor landing on the repository can orient themselves. You should also help the visitor navigate your repository (in whatever way you think is most appropriate). 

The next piece of information that your README should contain is an introduction to yourself.

__At the very least__, change `README.md` to something like "This is the repository of Jane Hacker", just to prove you have been there. Practice making a link, for example, to the [main STAT545 webpage](http://stat545.stat.ubc.ca).

Much better is to introduce yourself, showcasing a suite of GitHub-flavoured markdown functionality (you might find GitHub's [cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) useful for this). 

Here's a [sample readme file](https://github.com/STAT545-UBC/STAT545-home/blob/master/content/evaluation/hw01/sample_readme.md). The *Help* menu in RStudio will bring up a Markdown Quick Reference at any time.

## R Markdown for Gapminder exploration (40%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md): (20%)
	- Does your code run?
- [reasoning](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_reasoning.md): (20%)
	- How sensible is your exploration?

---

Make an R Markdown document that explores a dataset, such as gapminder seen in class. You don't need an extensive exploration in order to get a good grade here; a basic one will do, comparable to the one done in class. 

Don't forget! Render your R Markdown file to the `github_document` output format. Commit both the `.Rmd` and `.md` files and push them to GitHub. Give this a decent name, such as `hw01_gapminder.Rmd` (which will produce a companion file, `hw01_gapminder.md`).

## R Markdown presentation slides (15%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md): (5%)
	- Did you manage to produce slides at all?
- [reasoning](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_reasoning.md): (10%)
	- Is your slide deck formatted so that it actually looks like it could be a presentation? We _are not referring to_ whether your slides would make an _effective_ presentation (by, for example, minimizing your text and keeping your slides simple). By "formatted", we mean things like:
		- Slides do not have text overflowing its boundaries
		- Sentences are not cut in half by a new slide.
		- At least some slides have titles.

---

Produce slides out of your Gapminder exploration using R Markdown -- for example, using the `ioslides` or `xaringan` output. Don't worry, you won't be presenting these -- the objective of this exercise is to see that you can make slides. Feel free to make a new `.Rmd` file for this.

