---
title: "STAT 545A Assignment 02: Explore Gapminder and use dplyr"
---

__Due September 24, 2019 at 23:59__

## Objective

The goal is to get your feet wet with ggplot2 and dplyr to explore a dataset.

## Setup

Work with the `gapminder` data we explored in class, or more than one data set if you want.

The Gapminder data is distributed as an R package from [CRAN](https://cran.r-project.org/web/packages/gapminder/index.html). Install it if you have not done so already, by executing the code `install.packages("gapminder")`, and remember to load it with `library(gapminder)`.

Install and load `dplyr`, probably via the `tidyverse` meta-package.

## Tidy Submission (10%)

#### Mechanics (5%)

Follow the instructions for making a tidy submission, found on the [assignments home page](https://stat545.stat.ubc.ca/evaluation/assignments).

If there's any further uncertainty in determining a grade for this "mechanics" portion, the [UBC MDS mechanics rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_mech.md) will be referred to.

#### Writing (5%)

- You must use proper English, spelling, and grammar.
- You should write concisely. 
- If there's any further uncertainty in determining a grade here, the [UBC MDS writing rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_writing.md) will be used.

## Exercise 1: Basic `dplyr`

Use `dplyr` functions to achieve the following.

### 1.1 (9%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)
	- How successful were you at producing the required tibble?
	
---

Use `filter()` to subset the `gapminder` data to three countries of your choice in the 1970's.

### 1.2 (9%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)
	- How successful were you at producing the required tibble?
	
---

Use the pipe operator `%>%` to select "country" and "gdpPercap" from your filtered dataset in 1.1.

### 1.3 (9%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)
	- How successful were you at producing the required tibble?
	
---

Filter gapminder to all entries that have experienced a drop in life expectancy. Be sure to include a new variable that's the increase in life expectancy in your tibble. Hint: you might find the `lag()` or `diff()` functions useful. 

### 1.4 (9%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)
	- How successful were you at producing the required tibble?
	
---

Filter gapminder so that it shows the max GDP per capita experienced by each country.

### 1.5 (9%)

---

Rubrics:

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)
	- How successful were you at producing the required plot?

---

Produce a scatterplot of Canada's life expectancy vs. GDP per capita using `ggplot2`, without defining a new variable. That is, after filtering the `gapminder` data set, pipe it directly into the `ggplot()` function. Ensure GDP per capita is on a log scale. 


## Exercise 2: Explore individual variables with `dplyr` (15%)

---

Rubrics: 

- [reasoning](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_reasoning.md): (10%)
	- Does your exploration make sense?
- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md): (10%)
	- Does your code work?

---

Pick one categorical variable and one quantitative variable to explore. Answer the following questions in whichever way you think is appropriate, using `dplyr`:

* What are possible values (or range, whichever is appropriate) of each variable?
* What values are typical? What's the spread? What's the distribution? Etc., tailored to the variable at hand.
* Feel free to use summary stats, tables, figures.

## Exercise 3: Explore various plot types (30%)

---

Rubrics: 

- [reasoning](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_reasoning.md): (10%)
	- Were you able to produce plots that make sense?
	- We're not looking for publication quality graphics here yet.
- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md): (10%)
	- Does your code work?

---

Make two plots that have some value to them. That is, plots that someone might actually consider making for an analysis. Just don't make the same plots we made in class -- feel free to use a data set from the `datasets` R package if you wish.

1. A scatterplot of two quantitative variables.
2. One other plot besides a scatterplot.

You don't have to use all the data in every plot! It's fine to filter down to one country or a small handful of countries.


## Recycling (Optional) (extra 2%)

---

Rubrics: 

- [reasoning](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_reasoning.md)
	- How well did you reason through the scenario?

---

*For people who want to take things further.*

Evaluate this code and describe the result. Presumably the analyst's intent was to get the data for Rwanda and Afghanistan. Did they succeed? Why or why not? If not, what is the correct way to do this?

```
filter(gapminder, country == c("Rwanda", "Afghanistan"))
```

Read [What I do when I get a new data set as told through tweets](http://simplystatistics.org/2014/06/13/what-i-do-when-i-get-a-new-data-set-as-told-through-tweets/) from [SimplyStatistics](http://simplystatistics.org) to get some ideas!

## Tibble display (Optional) (extra 1%)

---

Rubrics: 

- [accuracy](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_reasoning.md)
	- Do your tibbles in this assignment adopt the required convention?

---

Present numerical tables in a more attractive form using `knitr::kable()` for small tibbles (say, up to 10 rows), and `DT::datatable()` for larger tibbles.

