---
title: "STAT 545A Assignment 04: Tidy data and joins"
---

__Due October 8, 2019 at 23:59__

## Objective

You have learned alot about data wrangling! You know how to use the tidyverse to:

* Filter rows and select variables in a principled or name-based manner
* Modify variables and create new variables
* Group rows of a data frame and do summarizing or mutating computations within group
* Reshape a data frame
* Get new information into a data frame via a joining

The goal of this homework is to solidify your data wrangling skills by working some realistic problems in the grey area between data aggregation and data reshaping.

If you internalize that there are multiple solutions to most problems, you will spend less time banging your head against the wall in data analysis. If something's really hard, sneak up on it from a different angle.

## Tidy Submission (10%)

### Mechanics (5%)

Follow the instructions for making a tidy submission, found on the [assignments home page](https://stat545.stat.ubc.ca/evaluation/assignments).

**NEW**: Like in Assignment 03, you are also expected to link to any html files that you produce, as a webpage. But, this time, this is only __if__ you produce an HTML file in your homework.

If there's any further uncertainty in determining a grade for this "mechanics" portion, the [UBC MDS mechanics rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_mech.md) will be referred to.

### Writing (5%)

- You must use proper English, spelling, and grammar.
- You should write concisely. 
- If there's any further uncertainty in determining a grade here, the [UBC MDS writing rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_writing.md) will be used.

## Exercise 1: Univariate Data Reshaping (30%)

Choose __\*EITHER\*__ "Univariate Option 1" or "Univariate Option 2". Both of these problems have three components:

1. Putting data in wider format;
	- 5%: Did you produce the [correct result](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)?
	- 5%: Code [quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md)
2. Producing a plot of the wide data; (10%)
	- 5%: Did you produce a sensible [visualization](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_viz.md)?
	- 5%: Code [quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md)
3. Re-lengthening the wider data. (10%)
	- 5%: Did you produce the [correct result](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)?
	- 5%: Code [quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md)

You are expected to use `pivot_wider()` and `pivot_longer()` for reshaping, and `ggplot2` for the plot.

Regarding the plot: 

- Don't worry about plotting _all_ of the data from the wide tibble. 
- The plot should be something that someone might actually want to produce in an analysis.

### Univariate Option 1

1. Make a tibble with one row per year, and columns for life expectancy for two or more countries. 
2. Take advantage of this new data shape to scatterplot life expectancy for one country against that of another.
3. Re-lengthen the data.

### Univariate Option 2

1. Compute some measure of life expectancy (mean? median? min? max?) for all possible combinations of continent and year. Reshape that to have one row per year and one variable for each continent. Or the other way around: one row per continent and one variable per year.
2. Is there a plot that is easier to make with the data in this shape versis the usual form? Try making such a plot!
3. Re-lengthen the data.


## Exercise 2: Multivariate Data Reshaping (30%)

Choose __\*EITHER\*__ "Multivariate Option 1" or "Multivariate Option 2". All of these problems have two components:

1. Putting data in wider format;
	- 8%: Did you produce the [correct result](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)?
	- 7%: Code [quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md)
2. Re-lengthening the data.
	- 8%: Did you produce the [correct result](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)?
	- 7%: Code [quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md)

Don't worry about producing a plot here. You are expected to use `pivot_wider()` and `pivot_longer()` for reshaping.

### Multivariate Option 1

1. Make a tibble with one row per year, and columns for life expectancy **and** GDP per capita (or two other numeric variables) for two or more countries. 
2. Re-lengthen the data.

### Multivariate Option 2

1. Compute some measure of life expectancy **and** GDP per capita (or two other numeric variables) (mean? median? min? max?) for all possible combinations of continent and year. Reshape that to have one row per year and one variable for each continent-measurement combination. Or the other way around: one row per continent and one variable for each year-measurement combination.
2. Re-lengthen the data.


## Exercise 3: Table Joins (30%)

Do __\*ALL\*__ of the activities in this section.

Read in the made-up wedding guestlist and email addresses using the following lines (go ahead and copy-paste these):

```
guest <- read_csv("https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/data/wedding/attend.csv")
email <- read_csv("https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/data/wedding/emails.csv")
```

Then, complete the following tasks using the tidyverse (`tidyr`, `dplyr`, ...). No need to do any pivoting -- feel free to leave `guest` in its current format.

__Rubric__: Each exercise is worth 10%, and is decomposed as follows:

- 5%: Did you produce the [correct result](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_accuracy.md)?
- 5%: Code [quality](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md)


### 3.1 (10%)

For each guest in the guestlist (`guest` tibble), add a column for email address, which can be found in the `email` tibble.

### 3.2 (10%)

Who do we have emails for, yet are not on the guestlist?

### 3.3 (10%)

Make a guestlist that includes everyone we have emails for (in addition to those on the original guestlist).