---
title: "Assignment 05"
author: "Your Name"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Assignment's goals
In this assignment, you will be improving the dashboard you created in assignment 4 by adding callbacks to core features and specifying the dashboard layout.
There are three tasks:
 
- Task 1: Create a plot with two callbacks
- Task 2: Update two plots based on the same input
- Task 3: Create a layout for your dashboard

## Task 1: Create a plot with two callbacks

You will be working with a histogram you created in Assignment 4 (Task 2.5).

### Task 1.1: Link dropdown menu to a plot (20%)

1. Link a dropdown menu from assignment 4 (Task 2.3) to the histogram graph: so that only data for the diamonds with a chosen clarity is plotted.
2. Make sure to add a line with annottaion or label to a dropdown explaining what the options mean (you can use `htmlP()` to add this, or `label=` option). For example of such annotation/label, refer to [Clinical Analytics Dashboard](https://dash-gallery.plotly.host/dash-clinical-analytics/) (e.g. "Select Admit Source").
3. Make sure that the histogram also has a title that updates based on what is being plotted. See example from [Class 8: Part3: Dynamically update a plot with a dropdown menu](https://stat545guidebook.netlify.com/dashr-part-ii.html) where the title of the plot "Change in <<VARIBALE>> over time" was updated based on the input from the dropdown.

### Task 1.2: Linking radial button to a plot(30%)

1. Create a radial button that changes y-axis of the histogram from linear/log (*Hint:* `scale_*_continuous()` is a very usefull function for making transformations on the axes or see class nots from Class 8 [Part4](https://stat545guidebook.netlify.com/dashr-part-ii.html)).
2. Link your radial button to the histogram graph. 
3. Both links for Tasks 1.1 and 1.2 should be placed in the same callback.
4. Make sure to add a line with annottaion /label to the radio button.

## Task 2: Update two Graphs based on the same input (20%)

In task 2 you will be working with the second plot (of your choice) you created in assignment 4 and also wil create one more new plot. Both plots will be linked to the same slider.

1. Use the second plot (of your choice) from assignmnet 4 .
2. Now create a new scatter/line plot (of your choice).
3. Link two plots from step 1 and 2 to a slider (so both plots will be updated based on the input from slider).
4. Make sure to add a line with annottaion /label to the slider.
5. Make sure that both plots have titles that contain information about quality of the cut. See example from [Class 8: Part3: Dynamically update a plot with a dropdown menu](https://stat545guidebook.netlify.com/dashr-part-ii.html) where the title of the plot "Change in <<VARIBALE>> over time" was updated based on the input from the dropdown.

## Task 3: Create a layout for your dashboard (30%)
You should choose one of the layouts from [this repo](https://github.com/matthewconnell/dashr_sample_layouts) created by Matthew as a starting point.
Apply the layout to your assignment.
