---
title: "Untitled"
author: "Your Name"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 05
In this assignment,you will be improving a dashboard created for assignmnet 4 by adding callbacks componnet to core features and specifying the dashboard layout. There are three tasks:
 
- Create a plot with two callbacks
- Update two plots based on the same input
- create a layout for your dashboard

## Task 1: One simple plot with minimum two call backs 

### Task 1.1: Linking dropdown menu (20%)

- link your dropdown menu from assignmnet 4 (Task 2.3) to the histogram graph (Task 2.5)
- make sute to add a line with annottaion to a slider explaining what the options mean ( You can use `htmlP()`as one of the options)
- make sure that histogram has a title
- title should contain information about dimond clarity 


### Task 1.2: Linking radial button (30%)
- create a radial button that changes y-axis of the histogram from linear/log
 *Hint:* `scale_*_continuous()` is a very usefull function for making transformations on the axes
 - make sute to add a line with annottaion to a radial button explaining what the options mean (You can use `htmlP()`as one of the options)
- link your radial button to the histogram graph in Task 2.5
- both links for task 1.1 and 1.2 should be placed in one callback

## Task 2: Update two Graphs based on the same input (20%)
- use the second plot (of your choice) from assignmnet 4 (task 2.5) 
- Using `ggplot`, create a third graph, line plot of your choice
- using a slider you created in assignment 4, link these two graphs, so that both graphs showed the data that corresponds to  the cut column of the diamonds dataframe.
- Make sure that both titles has infor about the diamonds cut displayed in teh graph

## Task 3: Create a layout for your dashboard (30%)
Here are some [examples](https://github.com/matthewconnell/dashr_sample_layouts) created by Matthew  that you can use as a template for your app

- Open a Terminal window (RStudio or system)
- Navigate to the appropriate folder using: `cd path/to/your/file/app.R`
- Type `Rscript app.R`
- Copy the address (numbers after start) and paste them into a browser window.
- Make sure the app works as you expect
